### ISSUE TITLE
Error while launching python comic.py

### ISSUE THREAD

**Issue by Adbs23** [ogkalu2/comic-translate#1]
ERROR    | modules.utils.download:get_models:47 - Model sha256: 8c0e395de8fa699daaac21aee33a4ba9bd1309cfbff03147813d2a025f39f349, expected sha256: 415a232fcb9d55b84fe76d859ac75c97987b76c2082c9c13d7f0c6a18c01f30d, wrong model deleted. Please restart comic-translate.

**Comment by ogkalu2** [comment]
I've updated the code and tested it. Should work now.

**Comment by Adbs23** [comment]
ok
