### ISSUE TITLE
ERROR: can't install "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by AniLuc** [ogkalu2/comic-translate#10]
Error:

![image](https://github.com/ogkalu2/comic-translate/assets/143954427/c380f889-41cf-4a20-a987-723c132b94b7)

**Comment by AniLuc** [comment]
Nope,
![image](https://github.com/ogkalu2/comic-translate/assets/143954427/8a863921-ebb0-4a00-928a-0f572f4a8fbf)
![image](https://github.com/ogkalu2/comic-translate/assets/143954427/1b5d2436-6dcb-4a7c-adc0-3856d8a81537)

**Comment by AniLuc** [comment]
I fixed the problem, the reason is that python was version x32.

**Comment by ogkalu2** [comment]
First of all, pick any package randomly in the txt file and manually install it. No need to include the version number. run:
pip install name of package 
Let's see if this is a dearpygui problem specifically

If there isn't any reason you installed the 32-bit version specifically then uninstall it, restart and install the 64 bit version of python and try again

If there is a reason then try running pip with the 32 bit version explicitly:
py -3.10-32 -m pip install -r requirements.txt

**Comment by ogkalu2** [comment]
> I fixed the problem, the reason is that python was version x32.

ah alright then
