### ISSUE TITLE
DEEPL and MICROSOFT translate error

### ISSUE THREAD

**Issue by vanderalex** [ogkalu2/comic-translate#100]
Then I try to translate by DEEPL (fr-ru, en-ru, fr-en) i have this error:
---------------------------
Error
---------------------------
An error occurred:
KeyError: 'Yandex'
---------------------------
OK   
---------------------------

**Comment by vanderalex** [comment]
Hey, please check deepl traslator!

**Comment by mansur54321** [comment]
I deleted the line “Yandex”: credentials['Yandex']['api_key'] in modules/translator.py”, line 215 and everything worked.

**Comment by ogkalu2** [comment]
I fixed this in the latest update (no need to delete anything)

**Comment by densnz** [comment]
> I fixed this in the latest update (no need to delete anything)

Traceback (most recent call last):
  File ".\comic-translate-main\controller.py", line 430, in translate_image
    if not is_there_text(self.blk_list) or not validate_translator(self, source_lang, target_lang):
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\comic-translate-main\modules\utils\pipeline_utils.py", line 181, in validate_translator
    if translator_tool == settings_page.ui.tr("Yandex") and not settings["credentials"]["Yandex"]["api_key"]:
                                                                ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'Yandex'

yo, how i can fix this?

**Comment by ogkalu2** [comment]
> > I fixed this in the latest update (no need to delete anything)
> 
> Traceback (most recent call last): File ".\comic-translate-main\controller.py", line 430, in translate_image if not is_there_text(self.blk_list) or not validate_translator(self, source_lang, target_lang): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ".\comic-translate-main\modules\utils\pipeline_utils.py", line 181, in validate_translator if translator_tool == settings_page.ui.tr("Yandex") and not settings["credentials"]["Yandex"]["api_key"]: ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^ KeyError: 'Yandex'
> 
> yo, how i can fix this?

Should be fixed. Try again now
