### ISSUE TITLE
Can't custom models be replaced?

### ISSUE THREAD

**Issue by lhj5426** [ogkalu2/comic-translate#104]
I thought I could use my custom-trained model specifically for Japanese comics by changing the model name, as shown in the picture
![image](https://github.com/user-attachments/assets/33ba3b9c-1851-48b6-9cd2-b4f3f382e471)

![image](https://github.com/user-attachments/assets/ab82b9d3-bce8-48e1-81f5-8aea044322e7)

![image](https://github.com/user-attachments/assets/48f1d473-eabc-4147-a2d5-3c945a26d757)
"But when I ran the software again, I found that it re-downloaded the original model, the one with the name before the change."
"By doing this, the software overwrote my renamed custom model. Can the functionality for adding custom models be included? This would allow me to easily use and test the models I have trained myself."
![image](https://github.com/user-attachments/assets/2a458c01-10ca-4065-aa3b-f5a6d4d9cd2f)
![image](https://github.com/user-attachments/assets/8bbf5b4e-ac21-4ed7-9b33-b7d8542b25ad)

https://github.com/xulihang/ImageTrans-docs/issues/711
"I trained a YOLOv8 model specifically for text recognition in Japanese full-color CG comics."

"I am also training a new model specifically for Japanese black-and-white and full-color comics."
 If custom models can be used, it would be very convenient."

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/79a9c72f-728f-41f6-a89c-c331b599dae7)
"Developer, the model you trained is not specifically trained for Japanese comics, so it performs poorly in text localization for Japanese manga."

**Comment by ogkalu2** [comment]
Are your custom models yolo models ?

**Comment by lhj5426** [comment]
"Of course, I only started learning how to use YOLOv8 to train models online in the last two months."
"I trained using the yolov8x.pt and yolov8s.pt models on a 3090 GPU."

nc: 6  # Number of classes
names: ['balloon','qipao','fangkuai','changfangtiao','kuangwai','other']
"I set up 6 classes and trained with the default 640x640 resolution. However, I only used 3 classes in practice."
balloon qipao changfangtiao
"I used this open-source program to manually label data day and night, often spending 16 hours a day labeling."
https://github.com/CVHub520/X-AnyLabeling
![image](https://github.com/user-attachments/assets/bd3fc40d-bf21-4a53-93b0-5e63655821d4)
![image](https://github.com/user-attachments/assets/177da3d1-8a26-41b2-9e3a-b8548a6b3cb7)
"I somewhat achieved the filtering of background onomatopoeia in scenes of two people in bed in Japanese manga. Background onomatopoeia is used to enhance the atmosphere and doesn't need to be recognized or translated. It was for this purpose that I started training my own model, and I have achieved an acceptable level of filtering."

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/36c671ec-971a-43ba-9ee9-ba07ca7056c7)
"This is the inference result for Japanese manga scenes of two people after converting your `comic-speech-bubble-detector` model to ONNX. As you can see, many background onomatopoeia words have been detected."

![image](https://github.com/user-attachments/assets/00c14f1c-f91c-4607-b3bd-375a11e28f72)
"This image shows the filtering effect of my own trained model on onomatopoeia in Japanese manga scenes with two people. As you can see, compared to your model, mine has better-targeted training for Japanese text. That's why I asked if custom models can be used."

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/f727bb4c-02ea-42a0-9e1e-c4fef6281516)
"Using the developer's software directly, some of it still gets recognized."

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/24247f04-8968-4292-8561-1f99212bd5b0)
"And there are also cases of missed detections, as shown in the image."

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/9991368b-4702-4945-9a63-d1409c8beb64)
"And the results for this type of content are even less ideal. This is the download link for the model I trained with yolov8s.pt, converted to ONNX format, specifically for full-color vertical text manga. Could this type of model be supported? Since GitHub does not support files larger than 10 MB, I used OneDrive for hosting."

Please provide the OneDrive link if you have it so that it can be reviewed.

https://alumnialbany-my.sharepoint.com/:f:/g/personal/planetrav_alumni_albany_edu/EnnR5gQvo2lMn162JRJJtrgBw1O0PWOG53NR26mSl2gNsg?e=3kyICe

**Comment by lhj5426** [comment]
"Alternatively, could the developer optimize the current model for recognizing Japanese manga text?"

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/415a32a3-eb9a-46b9-b231-3c96c7beda7a)
 "Such images even fail to achieve complete recognition."

**Comment by ogkalu2** [comment]
- Since they're yolo models, it's possible to switch but i have to make some changes to the code.
I have some questions:
- When there is no bubble but text exists, what class is the text predicted under ? does this class predict only this kind of text?
- How are you filtering background onomatopoeia ? Does it get predicted by a class ? If so, which class ?
- How many images did you train your model with ?
- which model is better ? medium or small ?

**Comment by lhj5426** [comment]
Unable to recognize anything like this, I didn't use any tags to indicate
as shown in the video

https://github.com/user-attachments/assets/147c9f9a-468f-4874-be08-ca58142eb55d

![image](https://github.com/user-attachments/assets/77d35b3a-1c9b-415b-9690-ef29062afa8d)
How to exclude onomatopoeic words?
When manually tagging, I don't tag images like this at all.
I only tag the required content text.
After tagging, iterative training is carried out repeatedly
to achieve the goal of filtering out onomatopoeic words.
For example, in an image like this,
there is no dialogue tagged for Xu Xiyuan at all.
It is the same as question one,
when there is no recognition, no tags are written


yolov8s.pt, the model placed in OneDrive, used over 10 GB and more than 8,400 images.
![image](https://github.com/user-attachments/assets/a06ff169-4b6f-4a76-97ca-546fac45fb53)

yolov8x.pt, which is still in training, used 27 GB and more than 24,000 images.
![image](https://github.com/user-attachments/assets/fb9f4a7e-e40f-4fc4-a202-16767f1f1742)

Regarding the recognition of comic text positions, I think the S model and the X model are actually similar. The only difference is the training speed and duration. I rent GPU services online for training, which costs 35-68 RMB per day, because I don't have GPUs like the 3090 or 4090 

Here is the translation of your provided text into English:

"Currently, using over 24,000 images on a 3090 to train the yolov8x.pt model takes about several dozen minutes to an hour per training epoch. In a day, I can train around 20 or fewer epochs. I have already trained for more than 150 hours, completing 155 epochs. Since my pocket money is exhausted, I am waiting to continue training next time."

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/1c357f72-97f8-4be6-a735-3d45192fbc9b)
![image](https://github.com/user-attachments/assets/942e2983-16b0-4019-a256-4441b4bbdce7)
![image](https://github.com/user-attachments/assets/ddae64e0-a05c-46d1-8137-809e9b117a7e)
![image](https://github.com/user-attachments/assets/7d6ab7a8-4c82-4378-8310-eeff42a690fc)

For the pure long strips and those with squares, I use the 'balloon' tag. For speech bubbles, I use the 'qipao' tag. For internal monologue descriptions with jagged bubbles, I also use the 'balloon' tag. Horizontal text is tagged with 'changfangtiao'. I mainly use these three tags to label the images, and I exclude onomatopoeic words during the labeling process

**Comment by ogkalu2** [comment]
Can you upload your difficult images to OneDrive or wherever? I want to do some testing.

**Comment by ogkalu2** [comment]
Would it be possible to share your 8400+ image dataset with me ?

**Comment by lhj5426** [comment]
https://alumnialbany-my.sharepoint.com/:f:/g/personal/planetrav_alumni_albany_edu/Eqj-2jSi979LlJ65sV5wUaIBUvHVon7N5KRi6VWcHM6fJQ?e=Lq11AS

**Comment by lhj5426** [comment]
All the images are from adult comics. Please open them carefully and try to do so when no one is around. Please be advised

**Comment by ogkalu2** [comment]
I have something preliminary working and I want to do some testing. Can you send the raw images (ie without any annotations) that are difficult for my model ?

**Comment by lhj5426** [comment]
Sure, but since the overall results were not satisfactory, I've selected a representative manga where your model didn't perform well. Here is the link for you to download it yourself.

https://e-hentai.org/g/2966365/494a78fbe7

https://hitomi.la/cg/%E3%82%A2%E3%83%80%E3%83%AB%E3%83%88dvd%E3%82%B3%E3%83%BC%E3%83%8A%E3%83%BC%E3%82%92%E8%A6%8B%E3%81%A6%E3%81%9F%E3%82%8D%E3%82%8A%E3%81%A3%E5%A8%98%E3%81%AB%E3%82%A4%E3%82%BF%E3%82%BA%E3%83%A9-%E6%97%A5%E6%9C%AC%E8%AA%9E-2986275.html#1

The text recognition in this manga series has a lot of missed detections. Let's use this as a representative example.
異世界エルフ発情の魔眼
https://hitomi.la/search.html?%E7%95%B0%E4%B8%96%E7%95%8C%E3%82%A8%E3%83%AB%E3%83%95%E7%99%BA%E6%83%85%E3%81%AE%E9%AD%94%E7%9C%BC

**Comment by ogkalu2** [comment]
I have pushed changes that merges the results of our models. Just download and run the update, you don't need to do anything else.
Since it merges results, some onomatopoeic words will register.
Even for just manga, merging results is in my opinion currently much better than using your model alone. Your model tends to predict text free of bubbles as single lines which makes rendering much harder (box is too small). 
When results are merged, it often groups multiple lines into one box. For example:
![Screenshot (264)](https://github.com/user-attachments/assets/da801934-99d8-4511-a5ea-f80ecc7e131d)
![Screenshot (265)](https://github.com/user-attachments/assets/52981319-eba0-457e-9fb7-ac95d09d22c2)

**Comment by lhj5426** [comment]
Haha, thanks! My model is specifically trained for another software, designed to handle single strips based on the software's features. The software itself has a merging function, and processing single strips makes OCR faster. Regardless, I want to express my gratitude!  I'll go update it and give it a try.

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/cfae5776-da31-40c1-91b6-316a667bb947)
![image](https://github.com/user-attachments/assets/150daa7d-086c-4163-b3e5-2a05a268b84e)

Much better now, but there are still two large, unclear squares remaining.
Especially in cases where it's just plain text.

**Comment by ogkalu2** [comment]
Send the first 2 images without the annotations

**Comment by lhj5426** [comment]
![AIA010118](https://github.com/user-attachments/assets/dbe0b7e6-1f67-435d-901a-b4a7e91f40d9)
![AIA010121](https://github.com/user-attachments/assets/545ae737-3691-4edf-9c43-1dfadd02ea9c)

**Comment by ogkalu2** [comment]
Fixed Now

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/d2cccb84-83fe-4bb6-a83c-fa44cd5d7a32)

Haha, no extra boxes this time. Thank you for your work!

**Comment by ogkalu2** [comment]
No Worries

**Comment by ogkalu2** [comment]
@lhj5426 
Your datasets files are corrupt. Can you upload it anywhere else ? Maybe Huggingface ?

**Comment by lhj5426** [comment]
https://github.com/user-attachments/assets/40c05de9-45d2-482b-a769-9ddd02e4c11a

This one?  
Please use Bandizip to extract it.  
I was able to upload it locally and extract it on the remote host without any issues.

**Comment by ogkalu2** [comment]
Yeah Thanks. My bad. Looks like the last file (009) didn't download properly
