### ISSUE TITLE
Wishlist for manual mode development

### ISSUE THREAD

**Issue by TaunT** [ogkalu2/comic-translate#109]
1) Add a control for setting a custom text color in a block and custom font size - **done**! https://github.com/ogkalu2/comic-translate/pull/114

![image](https://github.com/user-attachments/assets/07d698e0-5f46-4ceb-9c37-4d7c105e4305)

2) Add a control for line spacing

3) Buttons to reduce and increase all existing rectangles - really needed.
Now on each page you have to slightly reduce each rectangle each time. - **Done** https://github.com/ogkalu2/comic-translate/pull/112

4) option to disable outline on text - **done** https://github.com/ogkalu2/comic-translate/pull/110

**Comment by Sterben1579** [comment]
@TaunT  Where can I change the line spacing?

**Comment by TaunT** [comment]
@Sterben1579 
modules/rendering/render.py
line 123:
        draw.multiline_text(tbbox_top_left, translation, colour, font, align=blk.alignment, spacing=**1**)
to
        draw.multiline_text(tbbox_top_left, translation, colour, font, align=blk.alignment, spacing=**2**) or more)
