### ISSUE TITLE
Error "responses"

### ISSUE THREAD

**Issue by nemesis-github** [ogkalu2/comic-translate#11]
![image](https://github.com/ogkalu2/comic-translate/assets/58175736/abc7917b-2821-4c3f-a20c-43644b250770)

**Comment by nemesis-github** [comment]
Forming TextBlocks

**Comment by ogkalu2** [comment]
Can you try again using 'Default' for OCR. Same error ?

**Comment by nemesis-github** [comment]
![image](https://github.com/ogkalu2/comic-translate/assets/58175736/ee8cff62-9fd9-4416-87de-071b28d41946)
![image](https://github.com/ogkalu2/comic-translate/assets/58175736/922d4ac2-8d8d-412c-96d0-5a70c5486ea2)

**Comment by ogkalu2** [comment]
Try running this in a virtual environment.

python -m venv comic-venv

Make sure that you’re in the folder that contains the virtual environment you just created. Then:

venv\Scripts\activate

go to the directory of the comic folder

cd /path/to/comic-translate/

then 
pip install -r requirements.txt
python comic.py

**Comment by YasperMog1ot** [comment]
Same issue for me when translating english to russian while using google cloud vision, its okay with other OCR. Also app wraps text onto another line poorly sometimes. But overall experience is amazing, ty
