### ISSUE TITLE
Paste Translations Error

### ISSUE THREAD

**Issue by Sterben1579** [ogkalu2/comic-translate#113]
Hi again! I downloaded the latest version. I am getting an error while pasting the translations.

Traceback:
Traceback (most recent call last):
  File "C:\Users\anan_\comic-translate\app\thread_worker.py", line 30, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anan_\comic-translate\modules\rendering\render.py", line 87, in draw_text
    font = ImageFont.truetype(font_pth, size=init_font_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anan_\anaconda3\Lib\site-packages\PIL\ImageFont.py", line 819, in truetype
    return freetype(font)
           ^^^^^^^^^^^^^^
  File "C:\Users\anan_\anaconda3\Lib\site-packages\PIL\ImageFont.py", line 816, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anan_\anaconda3\Lib\site-packages\PIL\ImageFont.py", line 245, in __init__
    self.font = core.getfont(
                ^^^^^^^^^^^^^
OSError: cannot open resource

![02](https://github.com/user-attachments/assets/d7f2bcd1-bfba-4e38-849a-55660e96325c)

**Comment by notimp** [comment]
I'm not a dev, but OSError seems to indicate an issue thats originating by the Operating system, namely can not open some resource (a font file, or a file withing the comic-translate project folder).

If this is your first time trying to get comic-translate to run and it has not worked in the past, note that I installed it for the first time yesterday and everything works on a Windows 11 installation.

Here is how to get to my "point". :)

- win+r then enter %LOCALAPPDATA%\pip and delete the cache folder from there.
- run the python installer you downloaded again, and chose the uninstall option.
- download python-3.9.13-amd64.exe (if you are on Windows 11 - but essentially download python-3.9.13 and not any version thats newer than that. I tried it with the most current 3.10.* version first and got installation errors for the prerequisits it pulls)
- install python-3.9.13
- follow the installation instructions once more

Then only use the fonts supplied by comic-translate by default. And see if that solves your issue.

Or if you can pin down the problem further (as in does the error only occur, when you use a custom font that you provided...). If yes, copying the font file to the comic-translate folder also might solve your issue. (OSError cant open file, might be a permission issue of the font file being situated somewhere, where comic translate doesnt have the rights to read it from. It has permission to read its on folder though.. :) )

**Comment by notimp** [comment]
If that doesnt get you anywhere, the underscore in your username (anan_) might also cause an issue like this, if some calls in comic-translate were programmed badly. :) (But thats just guessing with nothing that that points that way.)
