### ISSUE TITLE
My final Request

### ISSUE THREAD

**Issue by Sterben1579** [ogkalu2/comic-translate#122]
Sorry for the inconvenience, but even though I understand what you wrote, I need to use translation to communicate. As a result, my sentences might lose some meaning.

Let me explain the idea I have in detail. First of all, our biggest issues are: "translation quality, text positioning, and text size," right? To quickly and easily address this issue, I have an idea. The method I'll discuss is intended to make the automatic mode more practical, but it also works well in manual mode.

What I suggest is adding a new step between the cleaning and text pasting stages. This new step would be a quality control stage. Before the translated texts are applied to the image, we should see the texts on the image in separate blocks, similar to the text addition feature in Photoshop. When we click on these text blocks, we should be able to make adjustments like "changing text content, repositioning by dragging, resizing text, and altering the text area," and most importantly, seeing this live. Later, when we click the paste translation stage, the texts will be applied to the image with their position, size, and area information.

Let me explain the advantage this provides in automatic mode, step by step:

We upload the images to the program.
We start the automatic mode, and it begins translating.
The program will pause at the quality control stage for each image and then move to the next image.
The automatic mode completes the translation.
We review all images at the quality control stage and make corrections for any incorrect translations and text adjustments.
There should be a "apply text to image" button somewhere in the program, which we will press. The program will process the images one by one with the adjustments we made.
This way, we will achieve a perfect quality comic book chapter by dedicating only 20 minutes to a single section.

This request might have seemed difficult at first, but actually, the only critical point is creating those text blocks. If we can achieve that, the rest will come easily since the program's structure is already suitable for this purpose.

Please feel free to ask any questions you may have. Let’s develop this program together.

**Comment by Sterben1579** [comment]
Actually, the text blocks I mentioned are similar to the ones in the image. When we add text in Photoshop, we can adjust its position and size by dragging the edges, and we can see these changes in real-time. This is exactly what I am requesting from you. Not being able to see how the text will look in the image in real-time is significantly slowing down our work.

For example, when the placement of a text is not perfect, I go through the following steps:

Step 1: Undo the image.
Step 2: Click on 'Segment Text' and then press the 'Clear Image' button, which takes about 5-10 seconds.
Step 3: Then I estimate the size and position of the text and click the 'Paste Text' button. It doesn’t turn out exactly as I want, so I have to repeat these three steps over and over. In some images, I have to do this 4-5 times, which results in a significant loss of time.

Does what I’m suggesting make sense? Is there a better way to approach this? Please, let's discuss it. I want this program to advance further. Let’s brainstorm. 

Also, could you add me on Discord for faster communication? 
My username is: Barbunay.

**Comment by notimp** [comment]
I think devs get what you (well all including me, to be honest) want, its just, that its very hard to implement, as reformating the text in a what you see is what you get fashion is not what the tool does. :) It looks at rectangle size, then decides what font size to use and how to split up the text. To have that step done instantly - while resizing the box, with the text always visible - is no small feat. :)

**Comment by TaunT** [comment]
@Sterben1579 It seems to me that your description is just some kind of unnecessary modification of the manual mode, I suggested another option and described it here https://github.com/ogkalu2/comic-translate/issues/117#issuecomment-2298222782 
All changes and corrections can be made when the auto mode has already processed all the images, and I have already even made changes for this, they are waiting for the approval of the author of the program https://github.com/ogkalu2/comic-translate/pull/121

**Comment by Sterben1579** [comment]
@TaunT 

I'd like to make a suggestion regardless of the topic. I want an additional area where we can manually set the font size and font for each block. While we can choose the minimum and maximum font size for each block, it would be more practical to directly enter the font size for convenience. If a manual font size is entered, it should disregard the min and max settings. Additionally, having to use the same font throughout the entire manga sometimes leads to a lack of emotional expression in some speech bubbles.

Also, could you call me on Discord when you have some time? I don't think I'm being clearly understood because I'm using translation. It would be better if I could explain visually through screen sharing.

**Comment by TaunT** [comment]
@Sterben1579 
1. `If a manual font size is entered, it should disregard the min and max settings.`
If you set min font = 15 and max font = 15 you will have fixed font = 15 =)

2. `Also, could you call me on Discord when you have some time? I don't think I'm being clearly understood because I'm using translation`
My native language is Russian, I understand English, but not everything, I speak a little and I think that in a direct conversation we will understand each other much worse than here with a translator) Don't worry, it seems like everyone understood what you want. It's just not very clear why, why your option is good and why you insist on this option.

**Comment by Sterben1579** [comment]
@TaunT 

Let me explain why I am requesting these features.

In manual mode, having to turn each image by pressing buttons one by one is a very time-consuming process.

scss
Kodu kopyala
Detect text - Wait
OCR - Wait
Translate - Wait
Segment text,
Clear screen - Wait
Paste text - Wait
Text is not aligned - Fix text and click the button again
Text still not aligned - Repeat the process
Going through all these steps for each image takes a lot of time. I want to handle all the steps in automatic mode and then go back to each image to fix any mistakes. However, after using the automatic mode, I can't edit the images anymore.

That's why we need a "semi-automatic mode." The program should process each image up to the final stage, but it should wait for our approval before moving on to the next image. If the text is not correct, we need to be able to modify it.

Also, please add a feature that allows us to visually review and edit the final translated text. Is it too difficult? Please explain why if it is. I'm even willing to donate $10 for this feature (which is a significant amount of money in my country).

After the image is processed, instead of showing red boxes, we need something that shows where the text will be placed, how it will look, and what size it will be. We should be able to click on the text and instantly adjust its size and font type. If you can do this, the program will be complete. This is my final request—I swear I won't ask for anything else.

Additionally, I also live in Turkey. We are both not very good at speaking English, but I think we can manage by using ChatGPT translations. I just need to be able to share my screen and explain what I want.

**Comment by ogkalu2** [comment]
@Sterben1579 
I understand your request fine. I even agree that such a feature would be very useful. It's something i would like to do but as @notimp said, it's not trivial to implement and there are other things i would like to do first. I can't make any promises.

**Comment by Sterben1579** [comment]
> @Sterben1579 I understand your request fine. I even agree that such a feature would be very useful. It's something i would like to do but as @notimp said, it's not trivial to implement and there are other things i would like to do first. I can't make any promises.

I'm eagerly and excitedly waiting !!!

**Comment by Sterben1579** [comment]
@ogkalu2 @TaunT @notimp 

Today, I wanted to record my screen while editing manga. I wanted to show why it takes 8 minutes just to translate a single page. If I could see the text live as I worked, this video wouldn't even be 3 minutes long. I'm constantly forgetting the position and size of the text, so I keep having to undo and make adjustments.
You can access the video from the link below.

https://streamable.com/3nmgmm

**Comment by TaunT** [comment]
@Sterben1579 
> Let me explain why I am requesting these features.
> In manual mode, having to turn each image by pressing buttons one by one is a very time-consuming process.
> scss Kodu kopyala Detect text - Wait OCR - Wait Translate - Wait Segment text, Clear screen - Wait Paste text - Wait Text is not aligned - Fix text and click the button again Text still not aligned - Repeat the process Going through all these steps for each image takes a lot of time.

Perhaps, it is true, we do not understand each other.
here https://github.com/ogkalu2/comic-translate/issues/117#issuecomment-2298222782  I described the AUTOMATIC mode with the ability to edit the last stages of text insertion. And I even already made it.
No need to press the Detect-OCR-Translate-Segment butons!

You upload 10 images, press TRANSLATE in auto mode and wait until ALL images are processed. After the program processes EVERYTHING, you can click on each image and correct only the last step of inserting the translation! There is an instruction there https://github.com/ogkalu2/comic-translate/pull/121#issue-2475760201.

For the selected processed image you press UNDO and get a clean image, press the button "Draw all the Text Blocks", move them, change, edit the text and press "Paste translations". This is more convenient than what you suggested with interrupting the program after each picture.

**Comment by Sterben1579** [comment]
@TaunT 
Did you see the video I posted above? I'm making an effort to align the text in the boxes. You can forget about the other changes I want; I just want to be able to make live changes to the text to escape this torment. If only there were text boxes instead of red boxes, and we could see the changes instantly with the adjustments we make from the right. That's my only wish. Please watch the entire video without skipping.

**Comment by TaunT** [comment]
@Sterben1579 Ok, then your wishes are transformed into one: to see the text in a rectangle in real time when changing the size of the field or font, right?

**Comment by Sterben1579** [comment]
@TaunT Exactly, but could you check the most recently opened topic to understand it better?

**Comment by TaunT** [comment]
@Sterben1579 I read all your requests, but I can't sympathize with you fully, because I see how few texts you have and how short they are and compare them with those that I which I translate and do not complain about my terrible fate 
Here are a few examples
![RCO022](https://github.com/user-attachments/assets/ee4d29e4-2869-443c-a7f7-bff2d7dd0d6b)
![RCO005 т](https://github.com/user-attachments/assets/066ea9ee-5718-46e1-bf1b-d24872ed3a72)

**Comment by lhj5426** [comment]
https://github.com/dmMaze/BallonsTranslator 

There are actually other open-source software of the same type.

**Comment by TaunT** [comment]
@lhj5426 
> There are actually other open-source software of the same type.
Thanks, this link has already been posted here. I liked it less than this comic-translate

**Comment by ogkalu2** [comment]
Implemented

**Comment by TaunT** [comment]
@ogkalu2 thanks, looks promising! but can't use it yet
The design style of text has changed a lot, I'll have to finish translating the current comic on the old version anyway, otherwise the differences will be obvious

in the individual block settings:
2) the maximum font setting has disappeared :(( It was necessary and convenient, there is a place for it
3) the general outline setting is not applied, you need to go and remove it manually in each block
4) THE MOST IMPORTANT THING is that the UNDO button does not cancel the rendering results, all blocks remain on the page with the text!

**Comment by ogkalu2** [comment]
2. It still uses that for the initial rendering of all the blocks. I don't know, i didn't really see the utility of that over resizing+Font size for individual blocks

3. For now, just untick the outline box on the main page before rendering(this should work. If it doesn't, let me know). I'll set the state of that to be the same as the general settings later. 

4. Yeah, I'll fix that later

**Comment by ogkalu2** [comment]
@TaunT 
> 2. It still uses that for the initial rendering of all the blocks. I don't know, i didn't really see the utility of that over resizing+Font size for individual blocks
> 
> 3. For now, just untick the outline box on the main page before rendering(this should work. If it doesn't, let me know). I'll set the state of that to be the same as the general settings later. 
> 
> 4. Yeah, I'll fix that later

**Comment by TaunT** [comment]
> @TaunT
> 2. It still uses that for the initial rendering of all the blocks. 
That's good, thank you.

> I don't know, i didn't really see the utility of that over resizing+Font size for individual blocks
This is necessary because it happens that initially in a foreign language there was a large text in the block, and after translation it became much smaller, it became short. And if there is no limitation of the maximum font, it will fill the entire block and will be gigantic. Adjusting its size to the rest of the texts is not very convenient.

**Comment by TaunT** [comment]
> For now, just untick the outline box on the main page before rendering(this should work. If it doesn't, let me know). I'll set the state of that to be the same as the general settings later.

It doesn't work. After the step of clearing the image on the screen there are no texts, no rectangles. I remove the stroke mark, but all the text still has a stroke. If I add rectangles with the button to pierce them all and remove the stroke on all, then they are drawn on the final image and cannot be removed in any way.

**Comment by TaunT** [comment]
If after rendering you add a new block and press Render again, it also remains pink and is not removed, plus all the blocks are added again

![image](https://github.com/user-attachments/assets/8100e358-1722-451b-8143-5cf51ea9f3db)

**Comment by TaunT** [comment]
And I would also like it if after moving the blocks in the render the changes were applied to the self.blk_list =)
Well, or until you save the project I will work in my old version, where I have saved and loaded

**Comment by TaunT** [comment]
@ogkalu2 There were comments above + another bug: After rendering, if we change the line spacing in a block, then when switching between blocks it does not change in the panel settings. It was applied to the blocks and saved, it is not loaded specifically into the settings.

**Comment by ogkalu2** [comment]
@TaunT 
Thanks for the Feedback. So i've fixed:
- Undo
- Adding new blocks with the box tool (Draw a box, select and add text in the original text edit area then click rendering again)
- Line Spacing, Bold/Italic/Underline and Alignment not properly reflecting in the UI for each block
- Duplicate Boxes, Conflicting Box/Text Items
- No Outline before rendering not reflecting for all blocks
- Outline and main text color now reflects the general settings on load

**Comment by ogkalu2** [comment]
> And I would also like it if after moving the blocks in the render the changes were applied to the self.blk_list =) Well, or until you save the project I will work in my old version, where I have saved and loaded

Just added this now

**Comment by TaunT** [comment]
@ogkalu2 Thank you very much! You have done a great, very useful and necessary work, and the application itself is excellent and very necessary)

**Comment by TaunT** [comment]
p.s. why I needed saving and loading - I usually go through the first stages - block detection, text recognition, translation, cleaning - and then it happens that the cleaning result is sad. Then I save the current state of the blocks, finish cleaning image in a graphic editor or even clean it all over again - save, open the cleaned picture in the program and load the previously recognized and translated blocks onto it, and then I do the rendering.

**Comment by TaunT** [comment]
@ogkalu2 

There is another problem, I didn't describe it yesterday because I thought it was obvious - when rendering, the rectangles are initially drawn much larger than the pink blocks were, you have to manually reduce each one. Is this how it's supposed to be or is it a bug?

![image](https://github.com/user-attachments/assets/74b45c9e-36a6-4a85-acd3-c436c7a73012)

![image](https://github.com/user-attachments/assets/e6f2f917-67bd-4e68-b7bc-7194d7a5b125)

**Comment by TaunT** [comment]
Another bug - when rendering, the default font type for all blocks is selected not from the global settings, but from the block settings panel of a specific block

![image](https://github.com/user-attachments/assets/10f6d273-72ba-4662-b8ec-91975f2d9a02)

**Comment by TaunT** [comment]
@ogkalu2 Alarm! I didn't notice right away ((( I've already managed to make 5 pages in the new version, and only then I saw - after exporting the finished result, the font quality is much worse than it was before! Argh, now I'll have to redo it again in the old version :(

This is how the text was written in the old version:

![image](https://github.com/user-attachments/assets/fdec4a79-f768-4940-b37f-d21ec3ebacbb)

And here's how it is now:

![image](https://github.com/user-attachments/assets/18a87f5c-b73a-44b9-8b17-5a322edff96e)

![image](https://github.com/user-attachments/assets/8bb68071-439a-4ca9-b420-f3f023671281)

**Comment by ogkalu2** [comment]
> @ogkalu2 Alarm! I didn't notice right away ((( I've already made 5 pages in the new version, and only then I saw - after exporting the finished result, the font quality is much worse than it was before! Argh, now I'll have to redo it again in the old version :( It's as if the final image is saved without anti-aliasing. On the program screen everything looks great, but when you save the image and then look at it - everything is bad.
> 
> This is how the text was written in the old version:
> 
> ![image](https://private-user-images.githubusercontent.com/1741557/362676510-aba9ee30-3409-4f34-bd55-2b851036a46e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NTI4ODUsIm5iZiI6MTcyNDk1MjU4NSwicGF0aCI6Ii8xNzQxNTU3LzM2MjY3NjUxMC1hYmE5ZWUzMC0zNDA5LTRmMzQtYmQ1NS0yYjg1MTAzNmE0NmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMTcyOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjA1M2JhMjAzOTNkM2FjOGZmZjQ2ODBkMTdkMDhmMTA3ZDQ0MmQ4MWRjYTkwNTI2NTBjYmZjYjc4NTNjNDAwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ye6T1vmtECUnXS2GHAtzGBfILCCqh2x9oD5zTePvq2Q)
> 
> And here's how it is now:
> 
> ![image](https://private-user-images.githubusercontent.com/1741557/362658912-18a87f5c-b73a-44b9-8b17-5a322edff96e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NTI4ODUsIm5iZiI6MTcyNDk1MjU4NSwicGF0aCI6Ii8xNzQxNTU3LzM2MjY1ODkxMi0xOGE4N2Y1Yy1iNzNhLTQ0YjktOGIxNy01YTMyMmVkZmY5NmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMTcyOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjY3YTkyYmQ5OGQ0YzA5OTkzOGM0ZmZlOTAyMDA0Y2VkM2E3YmNmZGE4NWUyYjMwYjQ4YTA3OThiZTRkMjQ3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HhUxMJyy7lIQRhTXUaxQMXx-M1RQILKlWNySv-aQPpY)
> 
> was before:
> 
> ![image](https://private-user-images.githubusercontent.com/1741557/362676164-03127264-a4f6-4ad5-bb7a-c5142bfdceae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NTI4ODUsIm5iZiI6MTcyNDk1MjU4NSwicGF0aCI6Ii8xNzQxNTU3LzM2MjY3NjE2NC0wMzEyNzI2NC1hNGY2LTRhZDUtYmI3YS1jNTE0MmJmZGNlYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMTcyOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDZjMGVmNzc0NDY2Y2JiZTJlYzU5N2JkMzY3YjBhMzE0YmEwNmIwMjM4OGMwNWQ3NmUxMGRhZTE2ODA3MjVmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.k__YNvw3po6SYP-bT696nh3rH-suSWVHvuWqPtuZY3M)
> 
> now:
> 
> ![image](https://private-user-images.githubusercontent.com/1741557/362660267-63742522-657b-401e-a4f9-7cc50ee4bd90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NTI4ODUsIm5iZiI6MTcyNDk1MjU4NSwicGF0aCI6Ii8xNzQxNTU3LzM2MjY2MDI2Ny02Mzc0MjUyMi02NTdiLTQwMWUtYTRmOS03Y2M1MGVlNGJkOTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMTcyOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzUyNjdkZTBmYTgyMTY5MjlhZWIwNDA0OWIzMTk4MDNkM2M4MmQzNmU0NGQzNGEyN2YyZWRmY2M1NWI3MjIxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D1boOepYDvQ5KOqmb59csXNBHGLwW5y1Rde1x-SYcTE)
> 
> upd: Interestingly, it also depends on the font size. In the screenshot below, the 14th font is anti-aliased, and the 11th is pixelated.
> 
> ![image](https://private-user-images.githubusercontent.com/1741557/362805983-fbc5657c-f3f6-4bdf-9cd5-a9f7ed4e91d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NTI4ODUsIm5iZiI6MTcyNDk1MjU4NSwicGF0aCI6Ii8xNzQxNTU3LzM2MjgwNTk4My1mYmM1NjU3Yy1mM2Y2LTRiZGYtOWNkNS1hOWY3ZWQ0ZTkxZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMTcyOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzlmMGJhZDQzOTFkZDliNzhiMjcyNDI0YzgyOTNmODdlNzljYWRlNzhjNmJhZGM3NGFlMDJjZjMxNmQ1ZDZlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pd0O2pjo5Jbus6MNmnkp1vy7qKaPqq6mSGtwi3Z6u2c)

I believe i've fixed this issue now (seems to correctly render now on my end). Check and let me know if it works for you.

**Comment by ogkalu2** [comment]
> p.s. why I needed saving and loading - I usually go through the first stages - block detection, text recognition, translation, cleaning - and then it happens that the cleaning result is sad. Then I save the current state of the blocks, finish cleaning image in a graphic editor or even clean it all over again - save, open the cleaned picture in the program and load the previously recognized and translated blocks onto it, and then I do the rendering.

I understand. It's definitely going to be implemented

**Comment by TaunT** [comment]
@ogkalu2 The font quality issue is fixed, thanks. But yesterday I discovered a new bug that makes it impossible to use the program - the image is not saved as the original, but only a small piece, or vice versa, a black stripe is added on one side.
Try adding text, zooming back and forth and saving.
And it doesn't matter whether you then returned to the reverse size - only a small part is saved crookedly

**Comment by ogkalu2** [comment]
@TaunT 
This is fixed now

**Comment by TaunT** [comment]
Thanks a lot!

**Comment by TaunT** [comment]
@ogkalu2 
![image](https://github.com/user-attachments/assets/779fbeac-b60d-431d-a5cd-0c5457459ece)

the text is saved in poor quality again(

**Comment by ogkalu2** [comment]
> @ogkalu2 ![image](https://private-user-images.githubusercontent.com/1741557/363036357-779fbeac-b60d-431d-a5cd-0c5457459ece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTI5MzQsIm5iZiI6MTcyNDk5MjYzNCwicGF0aCI6Ii8xNzQxNTU3LzM2MzAzNjM1Ny03NzlmYmVhYy1iNjBkLTQzMWQtYTVjZC0wYzU0NTc0NTllY2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMDQzNzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWE2NDkzZDIwZmJhNGI4NmQ1NjkzY2Y1ZjdhZDA4YjRmM2UwMTgyZmMwYjUzN2Y0OTViOGFlYmQ1OWU0NzRkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u_8sFiLvYpbqfw1tQtZCQLKLkENt1aCLzD7ztx4Ijeo)
> 
> the text is saved in poor quality again(

send the original picture

**Comment by ogkalu2** [comment]
@TaunT 
Also Try Again now

**Comment by TaunT** [comment]
@ogkalu2 Phew, everything seems to be fine now) Both the font and the save. Thanks again)

**Comment by TaunT** [comment]
@ogkalu2 Still, with a new rendering, the text boundaries are not preserved (If you Clean the image, then click Render and line up the texts, and then see something that is still not cleaned up, click Clean again and then Render - then the results of the first rendering will be reset, you will have to move all the boundaries again (

**Comment by ogkalu2** [comment]
@TaunT 
Should be fixed now

**Comment by TaunT** [comment]
@ogkalu2 This is great! I hope you are not offended by my coverage of bugs? I think if one person (like me) tells about them, and others do not have time to encounter them, then this will be a plus and will improve the overall impression of the program :)

So, one more thing, I don’t know if you are aware:
If you change the size of blocks after the Detect block step, then later on the Segment block step the old area is still painted over for cleaning, apparently it is created when creating blocks and is not updated when they are changed.

**Comment by ogkalu2** [comment]
@TaunT 
I don't mind. also, it's been fixed

**Comment by ogkalu2** [comment]
@TaunT @Sterben1579 
Since this feature has been implemented and major bugs resolved, i'm closing this.
