### ISSUE TITLE
 raw texts has a problem with text sort in new version

### ISSUE THREAD

**Issue by 9Panudet** [ogkalu2/comic-translate#128]
![Screenshot 2024-08-28 064251](https://github.com/user-attachments/assets/16e58977-1c1e-4467-a718-bf51261853b7)

**Comment by lawrenz1** [comment]
@ogkalu2 Should auto mode run `sort_blk_list`?

Or does auto mode use a different way to sort since `sort_blk_list` seems to only run in manual mode

**Comment by ogkalu2** [comment]
@lawrenz1 It should sort in auto mode too. I'll take a look and fix it.

**Comment by lawrenz1** [comment]
Nice I noticed the LLM translation is way better now with the fixed sorting
