### ISSUE TITLE
PDF Upload Fails in Latest Version Due to Unresolved Dependencies

### ISSUE THREAD

**Issue by mschmermer** [ogkalu2/comic-translate#131]
Description:

Since updating to the latest version, uploading PDF files no longer works. The process fails due to multiple unresolved dependencies, leading to a series of errors.

**Steps to Reproduce:**
- Update to the latest version of the comic-translate repository.
- Attempt to upload a PDF file.
- Observe the errors that occur during the upload process.

**Observed Behavior:**
The upload process fails immediately due to a missing dependency (fitz).
After attempting to resolve the fitz dependency manually, additional syntax errors and missing dependencies are encountered.

**Expected Behavior:**
PDF files should upload successfully without any missing dependencies or syntax errors.
Environment:

OS: macos & windows
Python version: 3.10
Version of comic-translate: main - latest
<img width="416" alt="image" src="https://github.com/user-attachments/assets/a0d222ab-99c5-431b-82be-07a801a19d7b">

**Comment by ogkalu2** [comment]
Resolved
