### ISSUE TITLE
Every image is dumped into memory at once

### ISSUE THREAD

**Issue by JohnKirk1337** [ogkalu2/comic-translate#137]
This takes way too much ram if the user loads too many images at once. The root of the problem is at line 387 of comic.py, in the method load_images_threaded. It just turns everything into 2d matrixes and dumps all of them into an array. It'd be better to load under demand, and at most load a couple of them ahead, and then unload when it's not being used.

**Comment by ogkalu2** [comment]
Resolved. But Left Hand View no longer loads images
