### ISSUE TITLE
Google Cloud Vision OCR division by zero error when inner_area is 0

### ISSUE THREAD

**Issue by lawrenz1** [ogkalu2/comic-translate#141]
In this example google vision ocr is matching this non-text block content as "de"
<img width="506" alt="image" src="https://github.com/user-attachments/assets/fc6254f7-c1d1-4fc2-92ff-e14bccef249e">

<img width="611" alt="image" src="https://github.com/user-attachments/assets/fce8bcb9-0b27-4589-a232-a5a7cf642c46">

Currently doing `if inner_area == 0:
        return False` in `is_mostly_contained` as a workaround

**Comment by ogkalu2** [comment]
Thanks for catching this. Updated the code to do the same
