### ISSUE TITLE
Encountering exceptions when bboxes is NoneType

### ISSUE THREAD

**Issue by lawrenz1** [ogkalu2/comic-translate#142]
For reference I think this textbox is an example where `bboxes` can result in `NoneType` 
<img width="92" alt="image" src="https://github.com/user-attachments/assets/e40c2c49-3ea2-4536-9e11-8fc3912f664b">

### 1. TypeError: object of type 'NoneType' has no len()

<img width="522" alt="image" src="https://github.com/user-attachments/assets/4799f353-3932-45af-a351-4ecd61ac5a1c">

https://github.com/ogkalu2/comic-translate/blob/c5468ba9f0760389a9bec7103c1d3e25b95484bf/comic.py#L706

https://github.com/ogkalu2/comic-translate/blob/c5468ba9f0760389a9bec7103c1d3e25b95484bf/comic.py#L719

I think these two lines need to be changed to `if bboxes is not None and len(bboxes) > 0: `

### 2. TypeError: 'NoneType' is not iterable

<img width="575" alt="image" src="https://github.com/user-attachments/assets/84ae70a2-99e1-448f-bcac-46b537c21e4f">

https://github.com/ogkalu2/comic-translate/blob/c5468ba9f0760389a9bec7103c1d3e25b95484bf/modules/utils/pipeline_utils.py#L95

I think `None` check for `bboxes` needs to be added in `generate_mask`

**Comment by ogkalu2** [comment]
fixed now
