### ISSUE TITLE
Feature Request: Load OCR from PDF

### ISSUE THREAD

**Issue by FuxorLuck** [ogkalu2/comic-translate#144]
The Program ITOP pdf can create OCR for free for the following langunges: French, Russian, German, Dutch, Spanish and Italian
and then save the PDF File with the OCR

https://www.iobit.com/en/recommend/pdf.php

However, the comic-translate program won't start the process of translation because it doesn't recognize the OCR from the PDF file, instead it requires me to pay extra money for ChatGPT API key for OCR

Can you please add an option to load OCR from PDF?

Thanks

**Comment by ogkalu2** [comment]
"Free" here would just mean me paying those fees instead of you. That's not going to happen.

**Comment by FuxorLuck** [comment]
I don't think you understand me

The PDF file already contains the data from the OCR scan, I just want the program to load it
