### ISSUE TITLE
cvtColor assertion error in detect_content_in_bbox when provided image array is empty [] because x1 == x2 in bbox

### ISSUE THREAD

**Issue by lawrenz1** [ogkalu2/comic-translate#145]
<img width="955" alt="image" src="https://github.com/user-attachments/assets/6c03aca8-d707-481d-ba9b-847023dfa4db">

I think the issue is that the image array can be empty if x1 == x2 in bbox

suggestion is to either adjust x coordinates or filter out bbox from the list if x1 == x2 ex.
`text_bounding_boxes = [bbox for bbox in text_bounding_boxes if bbox[0] != bbox[2]]`

**Comment by lawrenz1** [comment]
I just noticed https://github.com/ogkalu2/comic-translate/issues/120 which seems to encounter the same error message, but not sure if it is the same issue where x1 == x2 in bbox.

I will update this issue to be specific to the scenario when bbox x1 == x2 just in case

**Comment by lawrenz1** [comment]
> > <img alt="image" width="955" src="https://private-user-images.githubusercontent.com/6175019/371379030-6c03aca8-d707-481d-ba9b-847023dfa4db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NDg5NTksIm5iZiI6MTczMTQ0ODY1OSwicGF0aCI6Ii82MTc1MDE5LzM3MTM3OTAzMC02YzAzYWNhOC1kNzA3LTQ4MWQtYmE5Yi04NDcwMjNkZmE0ZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTJUMjE1NzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTI1Yjc3OGNjOTJjNGE3NDIwYjBhNTE1YzY5NGYwN2ExYWNmNTllNmQ3NTliOWQ0MDFhYWM0OWVjMzA3ZTc2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Hpn58EDHq2Ll9vzLLJcZidD86YGTO_zKmZsocTNgQFE">
> > I think the issue is that the image array can be empty if x1 == x2 in bbox
> > suggestion is to either adjust x coordinates or filter out bbox from the list if x1 == x2 ex. `text_bounding_boxes = [bbox for bbox in text_bounding_boxes if bbox[0] != bbox[2]]`
> 
> Does this resolve this issue for you ?

I think so, but it's been awhile since I tested the fix

**Comment by ogkalu2** [comment]
Implemented
