### ISSUE TITLE
Translated text not included in bulk export

### ISSUE THREAD

**Issue by nexalapp** [ogkalu2/comic-translate#149]
Hello, 

When I try to do a bulk export ("Export all images" button), the resulting zip file contains all pages with the original un-translated text removed, but the replaced translated text is also missing. There are only empty speech bubbles. However, if I manually export a single image ("Save currently loaded image" button), then it does correctly include the translated text. So far I have only used the 'manual' translation method. 

I've played around with the settings in the export tab of settings, but any combination of selections has yet to yield the translated text on bulk export. 

I have tried this with a windows PC and a Cuda GPU and on a M2 mac studio and both have the same result. Am I missing something, or is this a bug? Seems odd it would work in once place but not another.

Thanks for the support.

**Comment by ogkalu2** [comment]
Hey. Thanks for bringing this to my attention. Should be fixed now!

**Comment by ogkalu2** [comment]
Okay. It has actually been fixed now (Tested).
