### ISSUE TITLE
[question] the directory stuctrue is created manually or created by scaffold?

### ISSUE THREAD

**Issue by liaodalin19903** [ogkalu2/comic-translate#156]
I found that this PySide projects have such a project directory structure. 
```
app/
  projects/
  translations/
  ui/
docs/
models/
modules/
tests/

```

Is this manually created according to convention or is it laid out like this by default when creating a project?

**Comment by ogkalu2** [comment]
This would have been better in Discussions. But it's a structure i created personally, not really according to any convention. Just how i'd prefer it.
