### ISSUE TITLE
Bug: File not found: comic.py : update_image_history()

### ISSUE THREAD

**Issue by dEATh-PM** [ogkalu2/comic-translate#159]
When loading a project file with cleaned images, and therefore an image history, update_image_history will attempt cv2.imread(file_path) with the original file_path from the creation of the project.
This file will no longer exist if comic-translate has been closed and the old temporary working directory is removed and a new will have been created.

Log:
```CMD
Traceback (most recent call last):
  File "C:\AI\comic-translate\comic.py", line 311, in <lambda>
    worker.signals.result.connect(lambda result: QtCore.QTimer.singleShot(0, lambda: result_callback(result)))
  File "C:\AI\comic-translate\comic.py", line 1103, in <lambda>
    lambda result: self.display_image_from_loaded(result, index, switch_page=False),
  File "C:\AI\comic-translate\comic.py", line 556, in display_image_from_loaded
    self.display_image(index, switch_page)
  File "C:\AI\comic-translate\comic.py", line 693, in display_image
    self.load_image_state(file_path)
  File "C:\AI\comic-translate\comic.py", line 663, in load_image_state
    self.set_cv2_image(cv2_image)
  File "C:\AI\comic-translate\comic.py", line 601, in set_cv2_image
    self.update_image_history(file_path, cv2_img)
  File "C:\AI\comic-translate\comic.py", line 567, in update_image_history
    im = cv2.imread(file_path)
  File "C:\AI\comic-translate\venv\lib\site-packages\ultralytics\utils\patches.py", line 26, in imread
    return cv2.imdecode(np.fromfile(filename, np.uint8), flags)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Username\\AppData\\Local\\Temp\\tmpdfg57pzw\\unique_images\\_088.jpg'
```

I bodged in a check for the files existance before cv2.imread(file_path) on line 567 in comic.py :
```Python
if os.path.isfile(file_path):
  im = cv2.imread(file_path)
  cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
```
This workaround allows me to load the existing project without losing data, but is obviously not a fix to the problem.

**Steps to recreate:**
1. Start a fresh project
2. Clean one image
3. Save project
4. Close comic-translate
5. Open comic-translate (creating a new working directory in the tempfiles)
6. Open project
7. Navigate to cleaned image

**Comment by ogkalu2** [comment]
Replacing:
```
im = cv2.imread(file_path)
cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
```
with 
```
im = self.load_image(file_path)
```
in update_image_history() should fix the issue. Already pushed the update.

**Comment by dEATh-PM** [comment]
Perfect, it's all working as expected.
