### ISSUE TITLE
will there be an application release with an exe file, for ordinary people, I like to read comics, but I'm not good at Python

### ISSUE THREAD

**Issue by Furhfhdkd** [ogkalu2/comic-translate#16]
will there be an application release with an exe file, for ordinary people, I like to read comics, but I'm not good at Python

**Comment by ogkalu2** [comment]
When things are a bit more stable, I'll work on that. Right now it's much faster prototyping this way.

That said, you really don't need python or git knowledge to use this.

Maybe this would help ?

https://streamable.com/6j8b2g

**Comment by Kenryoku95** [comment]
please, that would be helpful

**Comment by Kenryoku95** [comment]
Is it available now in exe version? that would be really nice.
The video on streamable.com has been removed.
