### ISSUE TITLE
Error getting text translation

### ISSUE THREAD

**Issue by TaunT** [ogkalu2/comic-translate#163]
Several times I encountered the fact that the translation crashes with an error `No JSON found in the input string.`

I didn't really bother - I copied the entire text and pasted it into the chat.
But recently this began to happen on almost every page, I had to study the issue) It turned out that the incoming array is cut off. Probably, there are a lot of large texts in the comic.

I increased this parameter `max_tokens` to 5000 and it became normal. I recommend doing this permanently.

**modules/translator.py**

```
        response = self.client.chat.completions.create(
            model=model,
            messages=message,
            temperature=1,
            max_tokens=5000,
        )
```

I think this should be added in the next update.

**Comment by ogkalu2** [comment]
Done
