### ISSUE TITLE
Invalid CUDA 'device=0' requested.

### ISSUE THREAD

**Issue by DygDyg** [ogkalu2/comic-translate#17]
Ultralytics YOLOv8.1.3 🚀 Python-3.10.11 torch-2.1.0+cpu
An Error occurred: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: 0
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.
.

**Comment by DygDyg** [comment]
Video card: 3060ti

**Comment by DygDyg** [comment]
It helped me to remove torch torchvision:
pip uninstall torch touch vision
and install it version for CUDA 12.1: pop3 install torch torch vision touch audio --index-url https://download.pytorch.org/whl/cu121

**Comment by ogkalu2** [comment]
So you got it working in the end ?

**Comment by DygDyg** [comment]
> То есть, в конце концов, у вас все получилось?
Yes. 
For different cuda cores, different versions of torch are needed.
Perhaps you need to find out for which video adapters which versions are needed and add links to the installation description?
Via CMD: nvidia-sli, you can get information on CUDA. I have the CUDA Version: 12.4, version 12.1 is suitable for me.
![Screenshot_3](https://github.com/ogkalu2/comic-translate/assets/33259562/6478da86-382f-4586-9287-bb4e801d7f24)


There is a version for 11.8, I do not know which video cards are suitable for.
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`
