### ISSUE TITLE
Mining program running in the background?

### ISSUE THREAD

**Issue by Floresce** [ogkalu2/comic-translate#184]
When running this program, I found some really odd programs running in the background relating to /tmp/ultralytics_runner

It seems to take up a considerable amount of CPU usage show in htop while connecting to connect.consrensys.com However, upon further digging, that ultralytics_runner is actually an xmrig program. I suspect that the ultralytics package is compromised in PyPi. This program continues to run in the background even after comic-translate is closed.

When writing this up, it seems to align with a recent issue over at ultralytics https://github.com/ultralytics/ultralytics/issues/18027

![image1](https://github.com/user-attachments/assets/e44deb8a-eb6e-4519-aac2-4a1042e4fe56)

![image2](https://github.com/user-attachments/assets/fa8c9c2f-5014-40ac-bc13-9e05b20ed4c4)

**Comment by ogkalu2** [comment]
Thanks. It seems like 8.3.4 and earlier is uncompromised. I've updated the requirements to have that as a strict requirement.
