### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by KAMIL123421** [ogkalu2/comic-translate#20]
![image](https://github.com/ogkalu2/comic-translate/assets/158508596/d65d1aa5-878a-48b5-8df3-a1fed8f265b4)

**Comment by ogkalu2** [comment]
You need to run this before python comic.py:

pip install -r requirements.txt

**Comment by KAMIL123421** [comment]
![image](https://github.com/ogkalu2/comic-translate/assets/158508596/92138064-6761-4ebb-8c33-51081c00cd53)

**Comment by ogkalu2** [comment]
I updated the requirements file so download the code and try again. Also you should update pip with the command they describe in the image you just sent.

**Comment by ogkalu2** [comment]
@KAMIL123421 Everything working now ?

**Comment by KAMIL123421** [comment]
Yep,it work
