### ISSUE TITLE
erorr  No module named 'dearpygui'

### ISSUE THREAD

**Issue by nimfq** [ogkalu2/comic-translate#22]
![image](https://github.com/ogkalu2/comic-translate/assets/84028021/efdda230-0d7e-4007-9ed3-a4446030ec19)

**Comment by Tor-Saxberg** [comment]
@nimfq try this in a virtual environment. 
```
python -m venv manga
source manga2/bin/activate
```
replace paddleocr and paddlepaddle with PyMuPDF==1.23.8 in requirements.txt
```
pip install --upgrade pip
pip install -r requirements.txt
python comic.py
```
