### ISSUE TITLE
Error installing Torch

### ISSUE THREAD

**Issue by killo3967** [ogkalu2/comic-translate#31]
During installing dependencies, i have an error instaalling the vesion 2.1.0 of Torch. Then i saw the readme

If you have an NVIDIA GPU, then it is recommended to run

pip uninstall torch torchvision
pip install torch==2.1.0+cu121 -f https://download.pytorch.org/whl/torch_stable.html
pip install torchvision==0.16.0+cu121 -f https://download.pytorch.org/whl/torch_stable.html

But the same problem.

E:\comic translate\comic-translate-main>pip uninstall torch torchvision
WARNING: Skipping torch as it is not installed.
WARNING: Skipping torchvision as it is not installed.

E:\comic translate\comic-translate-main>pip install torch==2.1.0+cu121 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==2.1.0+cu121 (from versions: 2.2.0, 2.2.0+cpu, 2.2.0+cu118, 2.2.0+cu121, 2.2.1, 2.2.1+cpu, 2.2.1+cu118, 2.2.1+cu121)
ERROR: No matching distribution found for torch==2.1.0+cu121

E:\comic translate\comic-translate-main>pip install torchvision==0.16.0+cu121 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Ignored the following yanked versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3
ERROR: Could not find a version that satisfies the requirement torchvision==0.16.0+cu121 (from versions: 0.1.6, 0.2.0, 0.17.0, 0.17.0+cpu, 0.17.0+cu118, 0.17.0+cu121, 0.17.1, 0.17.1+cpu, 0.17.1+cu118, 0.17.1+cu121)
ERROR: No matching distribution found for torchvision==0.16.0+cu121

My python is:
E:\comic translate\comic-translate-main>python -V
Python 3.12.2

**Comment by killo3967** [comment]
You must say that is important to install CUDA Toolkit 12 from Nvidia in this url:
[](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html)

After this i visited and view that i could install 

pip install torchvision==0.17.0+cu121 -f https://download.pytorch.org/whl/torch_stable.h
tml

during the installation he install 
- https://download.pytorch.org/whl/cu121/torchvision-0.17.0%2Bcu121-cp312-cp312-win_amd64.whl
- https://download.pytorch.org/whl/cu121/torch-2.2.0%2Bcu121-cp312-cp312-win_amd64.whl
Now i could run the software, config the GPU and import a comic but i have the error "Can not open resource" and this is the log in the console:

E:\comic translate\comic-translate-main>python comic.py
C:\Users\tomas\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\tomas\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
2024-03-13 15:33:19.820 | INFO     | modules.inpainting.base:__call__:83 - hd_strategy: Resize
2024-03-13 15:33:19.828 | INFO     | modules.inpainting.base:__call__:108 - Run resize strategy, origin size: (2214, 1435, 3) forward size: (640, 415, 3)
2024-03-13 15:33:19.829 | INFO     | modules.inpainting.base:_pad_forward:61 - final forward pad size: (640, 416, 3)
An Error occurred: cannot open resource.

Last progress at Renderizando texto. Imagen 1 de 67

![image](https://github.com/ogkalu2/comic-translate/assets/71940871/ada3e927-0c67-4a78-ba02-799839c86824)

**Comment by WavaDev** [comment]
Please update the 'cu121' in '+cu121' to match your current CUDA version. The number '121' represents CUDA version 12.1. If you are running CUDA 11.8, replace '121' with '118'.
