### ISSUE TITLE
SyntaxError: invalid syntax. Perhaps you forgot a comma?

### ISSUE THREAD

**Issue by Junglep-W** [ogkalu2/comic-translate#32]
so how should I do with this?
<img width="687" alt="2" src="https://github.com/ogkalu2/comic-translate/assets/160207814/0f168344-911b-4684-a183-d2ccb9111569">

**Comment by WavaDev** [comment]
To open a normal Terminal/CMD in Windows and clone the "comic-translate" repository from GitHub, follow these steps:

1. Open File Explorer and navigate to the folder where you want to have the "comic-translate" project.

2. In the File Explorer address bar, replace the current file location with "cmd" and press Enter. This will open a Command Prompt window in that folder location.

3. In the Command Prompt window, execute the following command to clone the "comic-translate" repository:

   ```
   git clone https://github.com/ogkalu2/comic-translate
   ```

   This command will download the repository files to your current folder location.

Once the cloning process is complete, you will have a local copy of the "comic-translate" project on your Windows machine.

**Comment by Junglep-W** [comment]
Just start learning Python from 0, so... I'll be back maybe 1 year later
 
![error](https://github.com/ogkalu2/comic-translate/assets/160207814/24fffba2-f20e-4142-8d3f-f0c5935ca3e0)

**Comment by WavaDev** [comment]
You need to come the repository first, and then do pip install -r requirements.txt

**Comment by NartMaster** [comment]
Im having the same problem. Using Python 3.10 and nearly every command gives me a syntax error. I tried doing what you suggested in file explorer but windows cmd doesnt seem to recognize "git." Are there any more requirements I'm missing? Any chance a step by step guide could be given assuming the reader has never used python or even really github?

**Comment by ogkalu2** [comment]
@NartMaster 
Download and install git from here 
https://git-scm.com/downloads

alternatively, you could download the folder manually from github (click code > Download zip), open cmd in the comic-translate-main folder where all the files are located and follow the rest of the instructions.

**Comment by NartMaster** [comment]
Yeah, sorry about that, I guess I'm an idiot! Obviously I needed git... I also had like 3 versions of python installed so thats what was screwing my pip commands. Worked like a charm when I finally pulled my head out my ass and actually THOUGHT!
