### ISSUE TITLE
Module not found and dont know what it means.

### ISSUE THREAD

**Issue by KingDamo17** [ogkalu2/comic-translate#33]
Traceback (most recent call last):
  File "/comic-translate/comic.py", line 1, in <module>
    import dearpygui.dearpygui as dpg
ModuleNotFoundError: No module named 'dearpygui'

**Comment by WavaDev** [comment]
Have you done pip install -r requirements.txt?

**Comment by KingDamo17** [comment]
Yes, I went ahead and installed dearpygui on its own and i got through that error but then next I ran into : `Traceback (most recent call last):
  File "/Users/damosmacbook/comic-translate/comic.py", line 3, in <module>
    from modules.utils.download import get_models, mandatory_models
  File "/Users/damosmacbook/comic-translate/modules/utils/__init__.py", line 1, in <module>
    from .textblock import *
  File "/Users/damosmacbook/comic-translate/modules/utils/textblock.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
`
I thought all of these modules where in repo but maybe Im reading them wrong

**Comment by WavaDev** [comment]
If you have problems doing pip install -r requirements.txt, then download python version 3.10.10: https://www.python.org/downloads/release/python-31010/

**Comment by KingDamo17** [comment]
I ended up getting it to load the program after replacing `PyMuPDF==1.23.8` in the requirements.txt. I appreciate the help
