### ISSUE TITLE
Why are there not more languages in the target languages?

### ISSUE THREAD

**Issue by ocesta** [ogkalu2/comic-translate#38]
Can someone please tell me how to add Turkish language to the targeted languages?

**Comment by kaniatwo** [comment]
kanka bulabildin mi? 1 aydır bende uğraşıyorum. lütfen dc den geri dön 326662048270254091

**Comment by ocesta** [comment]
bulursan banada haber et

**Comment by kaniatwo** [comment]
kanka adama yazsana ben 2 aydır adamı taciz ediyorum mk sonunda yakında eklerim diye cevap aldım ama sende yaz, hızlandırsın gavat

**Comment by Sterben1579** [comment]
naptınız bulabildiniz mi yolunu?

**Comment by ogkalu2** [comment]
Turkish support added
