### ISSUE TITLE
Janpense something error

### ISSUE THREAD

**Issue by HimeYuyuko** [ogkalu2/comic-translate#40]
i install fugashi but it say fugashi can't import not only vscode, but also cmd. if use AMD chipset can't use this?

**Comment by ogkalu2** [comment]
AMD probably won't work if you've ticked the use GPU box. 

Can you post the exact error ?

**Comment by HimeYuyuko** [comment]
![image](https://github.com/ogkalu2/comic-translate/assets/69159983/16b73526-3a9f-4a60-bffd-0fb809320328)
setting
![image](https://github.com/ogkalu2/comic-translate/assets/69159983/0fe3e733-4ac0-4482-8a90-a99c80be92ab)
error

if i use local python 3.11 they say can't install requeriments.txt

**Comment by s87343472** [comment]
Python must be less than or equal to 3.10

**Comment by HimeYuyuko** [comment]
I resolve the problem using Pycharm
