### ISSUE TITLE
erreur python comic.py

### ISSUE THREAD

**Issue by LightMareOFFR** [ogkalu2/comic-translate#46]
Salut est que vous pouvez m'aider s'il vous plait merci beaucoup
![IMG_20240508_231200](https://github.com/ogkalu2/comic-translate/assets/169309602/90d7b66a-042c-48d8-ae6a-9b9a02561dea)

**Comment by WavaDev** [comment]
Have you done `pip install -r requirements.txt?`
Avez-vous fait `pip install -r requirements.txt?`

**Comment by WavaDev** [comment]
Run: `python -m pip install dearpygui`

**Comment by LightMareOFFR** [comment]
La j'est instalé deapygui est ca me fait ca 
C:\Users\User\Downloads\comic-translate-main\comic-translate-main>python -m pip install dearpygui
Collecting dearpygui
  Using cached dearpygui-1.11.1-cp310-cp310-win_amd64.whl (1.7 MB)
Installing collected packages: dearpygui
Successfully installed dearpygui-1.11.1
WARNING: You are using pip version 21.2.3; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

C:\Users\User\Downloads\comic-translate-main\comic-translate-main>python comic.py
Traceback (most recent call last):
  File "C:\Users\User\Downloads\comic-translate-main\comic-translate-main\comic.py", line 3, in <module>
    from modules.utils.download import get_models, mandatory_models
  File "C:\Users\User\Downloads\comic-translate-main\comic-translate-main\modules\utils\__init__.py", line 1, in <module>
    from .textblock import *
  File "C:\Users\User\Downloads\comic-translate-main\comic-translate-main\modules\utils\textblock.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by WavaDev** [comment]
Run: **pip install -r requirements.txt**

**Comment by LightMareOFFR** [comment]
c'est bon j'ai reussi
