### ISSUE TITLE
Problems encountered in translating Chinese

### ISSUE THREAD

**Issue by anchor554** [ogkalu2/comic-translate#49]
![212e793d98b5f697c5aff7be6014b4c](https://github.com/ogkalu2/comic-translate/assets/169419747/09f1597c-f828-4a07-83d4-46c69f790812)

I chose gpt4 and Google Cloud, but after the translation, all the content is garbled like this. Does anyone know how to solve it?

**Comment by WavaDev** [comment]
It is the font you chose. Choose a font that support chinese characters.

**Comment by WavaDev** [comment]
For example: `Noto Sans Simplified Chinese font`
