### ISSUE TITLE
How to solve this error that always occurs when translating comics?

### ISSUE THREAD

**Issue by anchor554** [ogkalu2/comic-translate#53]
![Uploading 0812b144beb32e59fc9c87b615abf17.png…]()

**Comment by anchor554** [comment]
[](url)
![0812b144beb32e59fc9c87b615abf17](https://github.com/ogkalu2/comic-translate/assets/169419747/0d3785ca-4e55-4eef-be1e-cfb43e89e24e)

**Comment by ogkalu2** [comment]
I want to see what settings you pick so screenshot the app. also what does your console say when it stops like this ?

**Comment by ogkalu2** [comment]
This has been solved with the latest update
