### ISSUE TITLE
Add Function to Select Multiple PDF Files for Translation

### ISSUE THREAD

**Issue by mschmermer** [ogkalu2/comic-translate#58]
Description
Enhance the file selection dialog to allow users to select multiple PDF files for translation at once.

Objective
Improve user experience by enabling the selection and translation of multiple PDF files simultaneously.

Proposal
Expand the file selection dialog to support multi-file selection.
Add a display to show all selected files before starting the translation.

**Comment by ogkalu2** [comment]
Resolved with v2
