### ISSUE TITLE
Add Yandex Translate service

### ISSUE THREAD

**Issue by RikCost** [ogkalu2/comic-translate#6]
You can add yandex translate in addition to google?
![image](https://github.com/ogkalu2/comic-translate/assets/69048938/b3c334eb-e104-4cbc-afd9-0270bdbed5cd)

**Comment by Muveeer** [comment]
+++++

**Comment by vanderalex** [comment]
+++++

**Comment by ogkalu2** [comment]
Done. You'll need an API key though
