### ISSUE TITLE
Error 400 policty violation

### ISSUE THREAD

**Issue by dawadazz** [ogkalu2/comic-translate#60]
Every two or three pages the program stop giving me this error. 
![Schermata del 2024-06-01 09-04-33](https://github.com/ogkalu2/comic-translate/assets/80988310/f31e6977-c458-4bd6-b634-baf4f194521f)

I use chatgpt 4o and translate from Spanish to Italian but it behaves like this with all the others. It seems to confuse these letters with captcha's to solve.
![015](https://github.com/ogkalu2/comic-translate/assets/80988310/39ad39bb-aadf-45db-9f9f-a3281a0aa8d5)
If I delete them manually the program works but it is 700 pages it would be too long.How can it be solved?thanks

**Comment by ogkalu2** [comment]
Download and try again. should be resolved now

**Comment by dawadazz** [comment]
It always gives me the same error even the new version, Error 400 policty violation

**Comment by ogkalu2** [comment]
I've just updated the app. There is now a new checkbox setting called "Provide Image to LLMs as context". It's ticked on by default. Untick it and see if the error is now gone.
