### ISSUE TITLE
Translate symbols shown

### ISSUE THREAD

**Issue by Kittyskj** [ogkalu2/comic-translate#63]
Translated image shows symbos
![0_translated](https://github.com/ogkalu2/comic-translate/assets/73357005/f3bd85f8-c84e-4a6a-bcfb-782a5d10af41)
![0](https://github.com/ogkalu2/comic-translate/assets/73357005/63aa0d5a-9132-4922-8c8e-ffc841619662)
![image](https://github.com/ogkalu2/comic-translate/assets/73357005/2080e926-a07c-449d-a31f-77efa3b58ca7)

**Comment by ogkalu2** [comment]
@Kittyskj This means you haven't selected a font that supports your target language (russian). Select NotoSans-Medium as your font

**Comment by Kittyskj** [comment]
> @Kittyskj This means you haven't selected a font that supports your target language (russian). Select NotoSans-Medium as your font

Ye thx i seen other issue and fixed that before
