### ISSUE TITLE
Google Cloud Vision sometimes getting an errıor

### ISSUE THREAD

**Issue by Sterben1579** [ogkalu2/comic-translate#65]
I have been doing a few tests since yesterday, and Google Cloud Vision sometimes randomly gives errors. When it gives an error, the program stops, causing problems. For example, I select 20 images. Sometimes it gives an error on 3-4 images, so it becomes exhausting to constantly find where the program left off. The errors I get are usually as follows:
'An Error occurred: 'y'.' or 'An Error occurred: 'x'.'
I think it's having trouble recognizing some texts properly. When I use default OCR on those pages, I can convert the image. However, the default OCR doesn't capture the texts as accurately, so it's not something I can use continuously.

I want to try using Microsoft OCR instead of Cloud Vision, but I don't know how to get the API key. Could you send me a link, like you did for Gemini?

I am attaching a random image that receives an error below:
![12](https://github.com/ogkalu2/comic-translate/assets/79475314/cf989397-920c-46fa-8e1f-078911e8d4f3)

**Comment by ogkalu2** [comment]
This has been fixed now with the latest update
