### ISSUE TITLE
block_reason: OTHER

### ISSUE THREAD

**Issue by NekoManga** [ogkalu2/comic-translate#66]
Sometimes it works without any issues, processing one or two images before giving an error.
Sometimes it processes 10 images before giving an error.
Sometimes it gives an error on the first page. I can't understand the problem.

![image](https://github.com/ogkalu2/comic-translate/assets/131636429/29b312a0-1b13-4a83-9597-15006ed489c8)

**Comment by ogkalu2** [comment]
This is the error the Gemini API returns when it has blocked your request for safety reasons. In the latest version of the app, there is now an option in settings to not provide the image as input to the LLM. If the content of the image itself is triggering the block then unticking it should resolve the issue. If it's the text triggering the block then unfortunately there's nothing i can do about it.
