### ISSUE TITLE
No module named "modules.utils"

### ISSUE THREAD

**Issue by Dioskard** [ogkalu2/comic-translate#7]
Traceback (most recent call last):
  File "C:\Users\vladi\Desktop\comic-translate\comic.py", line 3, in <module>
    from modules.utils.download import get_models, models_data
ModuleNotFoundError: No module named 'modules.utils'; 'modules' is not a package

Already downloaded all req, downloaded utils but not working

**Comment by ogkalu2** [comment]
Uninstall python. Run the installer again but make sure to tick
"Install Python to PATH" during the setup

Let me know if that works

**Comment by Dioskard** [comment]
Using python before for study, kind of prog and for stable diffusion (python 3.10 installed for it). Because of that path is confirmed (also add some kind of it to path myself with windows)

**Comment by ogkalu2** [comment]
are you running "python comic.py" directly/as is or from some other folder ?

**Comment by Dioskard** [comment]
directly from folder

**Comment by ogkalu2** [comment]
in the comic.py file, after line 2 (import os), add

import sys
print(f'Running from {os.getcwd()}')
sys.path.insert(0, os.getcwd())

See if this works

**Comment by Dioskard** [comment]
#move folder from desktop to disk

**Comment by Dioskard** [comment]
BTW, found something. when i renamed folder modules to modls and change it also in comic.py and pipeline.py it's work...
I think my python was trying to find real modules.py from python folder in appdata

**Comment by Dioskard** [comment]
And now it's error responses... 
![image](https://github.com/ogkalu2/comic-translate/assets/117338891/5058e783-ee69-47d4-bdfc-5a8a0f52f8db)

**Comment by ogkalu2** [comment]
Okay so the Gui loads now?

What progress does the error start at ? i.e 'forming textblocks', 'Translating' etc

**Comment by Dioskard** [comment]
![image](https://github.com/ogkalu2/comic-translate/assets/117338891/5191c84b-43ca-40b2-86be-0950d0ac4059)
Gui working. This settings and now it's translate i t
hink somehow? But it's translate to [] and some text is not translated
![10_translated](https://github.com/ogkalu2/comic-translate/assets/117338891/d0a44dbf-96cb-4cdf-b852-66c72c76be18)

**Comment by ogkalu2** [comment]
Change your Font to Notosans Medium. animereg does not support Russian.
