### ISSUE TITLE
I have a new suggestion.

### ISSUE THREAD

**Issue by Sterben1579** [ogkalu2/comic-translate#70]
There is a lot of meaning loss when translating images one by one into the language I want, even when I use GPT-4. It makes the mangas feel emotionless as if a robot is speaking. This is probably because the story from previous pages is not known. Now I have 2 suggestions for you. Can you add one of them if it is not too much trouble?

Suggestion 1: Having a way to correct the translated texts before embedding them into the image. While this would be very useful for us, it might reduce the practicality a bit.

Suggestion 2: Processing all the added images in sequence and sending all the images for translation at once. This would greatly reduce the cost since we would send the system prompt only once instead of every time. I also believe this would result in incredibly high-quality translations. After receiving the response, it could then embed the translations into the images one by one. According to my calculations, this would halve the cost. Of course, since this may not suit every user, it would be great to have an on/off switch in the settings.

**Comment by Sterben1579** [comment]
Additionally, thank you for sharing this amazing program with us. When the quality of artificial intelligence has reached this level, I found it incredibly difficult to wait weeks for a new chapter. This program has been a lifesaver.

**Comment by Sterben1579** [comment]
I guess you didn't like my suggestions.

**Comment by ogkalu2** [comment]
@Sterben1579 

Hey. Sorry I didn't reply. I've actually been working on a Manual Mode for this app (where you can draw up your own text boxes or look at and edit the OCR Text or Translations so I've been kinda busy)

Your suggestions aren't bad. Although I don't know about pasting the context of the entire chapter or so. That's a huge cost upturn I think. Currently, the LLMs see the entire text for the page. If at say pay 5, I'm also pasting in all the text for the previous 5 pages, that's a lot more context. I'll think about it though. I may implement it as an Optional settings.

**Comment by Sterben1579** [comment]
If you could add a feature that allows us to edit text on images, move it around, or resize it just like in Photoshop, it would be amazing. I initially suggested sending all the images at once to improve translation quality because I didn't think this was possible. However, your suggested method would be incredible. Being able to edit the images would make all our tasks much easier.

**Comment by ogkalu2** [comment]
Ok so you don't get too excited, it's not going to be like photoshop. It's just well, the whole process is broken up into parts right ?

First the bubble and text detectors, then OCR, then Inpainting, the getting the translations then Pasting them. 
Each of those steps could introduce failure modes. What i'm doing is you being able to correct the aftermaths of those steps. So if the bubble detector misses a bubble then you can just draw the area manually or if the OCR isn't quite right, then you can correct the text in a separate text box on the screen before it gets translated and so on.

**Comment by Sterben1579** [comment]
Even the features you mentioned above would make our work so much easier. Let me explain why. I have actually been facing an issue for the past few days. I translate from English to Turkish, and mangas often split one sentence into 2 or 3 speech bubbles. English and Turkish have very different sentence structures. So, when those types of bubbles are translated, the resulting sentence structure is very awkward. If you could add a feature to manually adjust translated sentences or manually delete speech bubbles, it would be incredible. I'm eagerly looking forward to it.

**Comment by Sterben1579** [comment]
After coming across your program, I created a random project and registered for the Microsoft Startup program. I received a $2500 credit from OpenAI. The $2500 credit is just waiting to be used for manga translations :D 👍

**Comment by Sterben1579** [comment]
> > After coming across your program, I created a random project and registered for the Microsoft Startup program. I received a $2500 credit from OpenAI. The $2500 credit is just waiting to be used for manga translations :D 👍
> 
> Hello, can you explain how you got the loan? Frankly, I would be very happy, I don't have a budget and I have to constantly top up the balance.

Where are u from mate?



> ogkalu2

Hello "ogkalu2," how are you? I see that a new update has arrived. Is it an update with the new features we discussed or just a bug fix update? I was eagerly waiting for your new update.

**Comment by ogkalu2** [comment]
> Hello "ogkalu2," how are you? I see that a new update has arrived. Is it an update with the new features we discussed or just a bug fix update? I was eagerly waiting for your new update.

It's not the new update. Just bug fixes and an updated Readme. I'll let you know when that's done. Might take a week or two.

**Comment by Sterben1579** [comment]
> It's not the new update. Just bug fixes and an updated Readme. I'll let you know when that's done. Might take a week or two.

I am eagerly awaiting the new update. I’m so excited about it that I can hardly sleep at night. Is there an estimated release date?

**Comment by ogkalu2** [comment]
@Sterben1579 Today Probably. Maybe Tomorrow

**Comment by ogkalu2** [comment]
It's up now
