### ISSUE TITLE
empty text error

### ISSUE THREAD

**Issue by NekoManga** [ogkalu2/comic-translate#73]
Actually there was a balloon but he couldn't detect it.
Since there is nothing else, it gives an error and the bot stops.
If he couldn't detect the text, I think he should skip that page instead of getting corrupted and copy the original source directly.
![image](https://github.com/ogkalu2/comic-translate/assets/131636429/cac123d9-ef98-4975-a63e-41b6944c8903)

**Comment by ogkalu2** [comment]
Can you try again with the latest update and see if you still have the error ?
