### ISSUE TITLE
An Error occurred: zero-size array to reduction operation minimum which has no identity.

### ISSUE THREAD

**Issue by JohnKirk1337** [ogkalu2/comic-translate#77]
![brave_rNzdvuh2jM](https://github.com/ogkalu2/comic-translate/assets/59065439/33b17d6c-aa44-4ca1-a83f-606357b2e25b)

This happens to one specific image.

OS:

- Edition Windows 11 Pro
- Version 24H2
- Installed on ‎16/‎06/‎2024
- OS build 26100.1000
- Experience Windows Feature Experience Pack 1000.26100.6.0

Hardware:

- Processor AMD Ryzen 5 5600G
- Installed RAM 32,0 GB
- GPU NVIDIA GeForce RTX 3060

**Comment by ogkalu2** [comment]
Can you try again with the latest update and see if you still have the error ?
