### ISSUE TITLE
How you detect the panel reading order of the manga and BD?

### ISSUE THREAD

**Issue by jojogh** [ogkalu2/comic-translate#80]
How you detect the panel reading order of the manga and BD?

**Comment by ogkalu2** [comment]
It's harcoded right now. If the source language is Japanese, i assume it's read vertical_right to left. For everything else, i assume horizontal_left to right. 

The code itself can handle all four though:
vert_rtl
vert_ltr
hor_rtl
hor_ltr

**Comment by jojogh** [comment]
ok,thanks
