### ISSUE TITLE
ignore errors when translating large files, save the intermediate result

### ISSUE THREAD

**Issue by TaunT** [ogkalu2/comic-translate#86]
### Discussed in https://github.com/ogkalu2/comic-translate/discussions/85

<div type='discussions-op-text'>

<sup>Originally posted by **TaunT** July 21, 2024</sup>
Several times when translating a CBZ file, the program crashed with an error and stopped translation. This is very unpleasant, considering that each request, for example, to GPT4 costs money and the intermediate result of translating 10-20 pages was not saved anywhere. Can you make an option to intercept such errors? If some page is not successful, then the program ignores it, leaves its original version and moves on, and then at the end it writes which pages are untranslated so that you can complete them one by one. Otherwise, now I have to manually do everything one image at a time (((</div>

**Comment by TaunT** [comment]
Error example "An Error occurred: Expecting value: line 1 column 1 (char 0)."

**Comment by ogkalu2** [comment]
Yeah I'll work on that. The next update will at least have the images that did work accessible in the comic-translate folder so you don't have to start over.

**Comment by TaunT** [comment]
Thank you very much for your work!
I would like to note one more point - the cleaning module works very poorly if some words inside the text were highlighted in bold

**Comment by ogkalu2** [comment]
Resolved with the latest update
