### ISSUE TITLE
poor performance of the Inpaiting module

### ISSUE THREAD

**Issue by TaunT** [ogkalu2/comic-translate#89]
For me this is the biggest problem, it is very difficult for module to clear the text and because of this it cannot insert a translation. Can you make a choice of inpainting algorithm, like for the translator and the OCR?

1) original
![RCO008-gigapixel-low resolution v2-2x HARD](https://github.com/user-attachments/assets/484da9aa-8584-4217-b4a6-2927135df19b)

2) cleaned
![RCO008-gigapixel-low resolution v2-2x HARD_cleaned](https://github.com/user-attachments/assets/bb118160-f3ac-4d7d-8391-9be933cbba94)

3) translated
![RCO008-gigapixel-low resolution v2-2x HARD_translated](https://github.com/user-attachments/assets/bd9f68a9-8eac-4b99-9718-3491ac84aa1e)

(the translation text is very bad, because for this page I chose a free Google translator for experiments)

**Comment by TaunT** [comment]
Are there any hints or tips, maybe I can change the values ​​in the config parameters to make it clean better?
I didn't find it myself(

**Comment by ogkalu2** [comment]
I'm going to push an update later today. You will be able to manually clean the Images. Still only one Inpainting model but i've laid grounds to add support for more later easily.

**Comment by ogkalu2** [comment]
After some algorithmic improvements and reworking how segmentation works entirely, inpainting is much better. 
For example your image on automatic mode(Inpaint resize method - 960) now returns
![en_cleaned](https://github.com/user-attachments/assets/36ce3d4f-aee0-4fbd-9818-ac5ed8476760)
![en_translated](https://github.com/user-attachments/assets/1c62bf76-4105-407f-9536-a88d941972bf)

**Comment by TaunT** [comment]
@ogkalu2 Thank you very much! I have already tried it and it is amazing! Much better than before, now I don't have to manually fix clouds that used to have broken borders. It saves a lot of time and nerves, thanks again, great!

**Comment by TaunT** [comment]
Unfortunately, I can only use manual mode for now, probably because of the complexity of the Russian language, so I make different conveniences for myself in my branch) I made two requests. The second - with disabling the text outline, it seems to me, you can easily integrate it into your project.

![image](https://github.com/user-attachments/assets/53e9a5cc-61ab-43d2-b333-f3e96112fe79)

**Comment by ogkalu2** [comment]
@TaunT No problem. I just added some comments on your second pull request (outline). You just need to make a few very small changes. I can make the changes myself if you don't mind.

**Comment by TaunT** [comment]
@ogkalu2 done! =)

**Comment by ogkalu2** [comment]
Thanks! Merged.

**Comment by TaunT** [comment]
@ogkalu2 my manual mode panel now)
![image](https://github.com/user-attachments/assets/8932e6b2-6b8b-4f0b-8e60-18526c3f3ad7)
