### ISSUE TITLE
Run ERROR

### ISSUE THREAD

**Issue by BomberCreeper** [ogkalu2/comic-translate#9]
![Screenshot_63](https://github.com/ogkalu2/comic-translate/assets/81633713/e0221118-8ea3-4fa9-9783-b200fb0a24d1)

**Comment by ogkalu2** [comment]
Can you show me the output of pip freeze ?

**Comment by BomberCreeper** [comment]
> Can you show me the output of pip freeze ?
> 
> Also paste the Error as text rather than an Image.

PS C:\Users\dimas> cd C:\comic-translate-main
PS C:\comic-translate-main> python comic.py
Traceback (most recent call last):
  File "C:\comic-translate-main\comic.py", line 3, in <module>
    from modules.utils.download import get_models, models_data
  File "C:\comic-translate-main\modules\utils\download.py", line 2, in <module>
    from torch.hub import download_url_to_file
  File "C:\Users\dimas\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 139, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\dimas\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies.
PS C:\comic-translate-main> pip freeze
WARNING: Ignoring invalid distribution -orch (c:\users\dimas\appdata\local\programs\python\python310\lib\site-packages)
annotated-types==0.6.0
anyio==4.2.0
astor==0.8.1
attrdict==2.0.1
azure-ai-vision-imageanalysis==1.0.0b1
azure-core==1.29.7
Babel==2.14.0
bce-python-sdk==0.9.2
beautifulsoup4==4.12.3
blinker==1.7.0
Brotli==1.1.0
cachetools==5.3.2
certifi==2023.11.17
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
contourpy==1.2.0
cssselect==1.2.0
cssutils==2.9.0
cycler==0.12.1
Cython==3.0.8
dearpygui==1.10.1
decorator==5.1.1
deep-translator==1.11.4
deepl==1.16.1
Deprecated==1.2.14
distro==1.9.0
easyocr==1.7.1
EbookLib==0.18
emoji==2.10.0
et-xmlfile==1.1.0
exceptiongroup==1.2.0
filelock==3.13.1
fire==0.5.0
Flask==3.0.1
flask-babel==4.0.0
fonttools==4.47.2
fsspec==2023.12.2
future==0.18.3
h11==0.14.0
httpcore==1.0.2
httpx==0.26.0
huggingface-hub==0.20.3
idna==3.6
imageio==2.33.1
img2pdf==0.5.1
imgaug==0.4.0
inflate64==1.0.0
isodate==0.6.1
itsdangerous==2.1.2
jaconv==0.3.4
Jinja2==3.1.3
kiwisolver==1.4.5
largestinteriorrectangle==0.2.0
lazy_loader==0.3
llvmlite==0.41.1
lmdb==1.4.1
loguru==0.7.2
lxml==5.1.0
MarkupSafe==2.1.4
matplotlib==3.8.2
mpmath==1.3.0
multivolumefile==0.2.3
networkx==3.2.1
ninja==1.11.1.1
numba==0.58.1
numpy==1.26.3
openai==1.8.0
opencv-contrib-python==4.6.0.66
opencv-python==4.6.0.66
opencv-python-headless==4.9.0.80
openpyxl==3.1.2
opt-einsum==3.3.0
packaging==23.2
paddleocr==2.7.0.3
paddlepaddle==2.5.2
pandas==2.2.0
pdf2docx==0.5.8
pikepdf==8.11.2
pillow==10.2.0
premailer==3.10.0
protobuf==3.20.2
psutil==5.9.8
py-cpuinfo==9.0.0
py7zr==0.20.8
pybcj==1.0.2
pyclipper==1.3.0.post5
pycryptodome==3.20.0
pycryptodomex==3.20.0
pydantic==2.6.0
pydantic_core==2.16.1
PyMuPDF==1.20.2
PyMuPDFb==1.23.7
pyparsing==3.1.1
pyppmd==1.1.0
python-bidi==0.4.2
python-dateutil==2.8.2
python-docx==1.1.0
pytz==2023.4
PyYAML==6.0.1
pyzstd==0.15.9
rapidfuzz==3.6.1
rarfile==4.1
regex==2023.12.25
requests==2.31.0
safetensors==0.4.2
scikit-image==0.22.0
scipy==1.12.0
seaborn==0.13.2
shapely==2.0.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.5
stanza==1.7.0
sympy==1.12
termcolor==2.4.0
texttable==1.7.0
thop==0.1.1.post2209072238
tifffile==2024.1.30
tokenizers==0.15.1
toml==0.10.2
torch==2.1.0
torchvision==0.16.0
tqdm==4.66.1
transformers==4.36.2
typing_extensions==4.9.0
tzdata==2023.4
ultralytics==8.1.3
urllib3==2.1.0
visualdl==2.5.3
Werkzeug==3.0.1
wget==3.2
win32-setctime==1.1.0
wrapt==1.16.0

**Comment by ogkalu2** [comment]
Do you have an Nvidia GPU ?

Try:
pip uninstall torchvision torch
pip install torch==2.1.0+cu121 -f https://download.pytorch.org/whl/torch_stable.html
pip install torchvision==0.16.0+cu121 -f https://download.pytorch.org/whl/torch_stable.html

change 121 to 118 if your cuda version is 11.8 rather than 12.1

**Comment by BomberCreeper** [comment]
> Do you have an Nvidia GPU ?
Yes, I have Nvidia.


C:\comic-translate-main>pip install torch==2.1.0+cu121 -f

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-f option requires 1 argument

C:\comic-translate-main>pip install torchvision==0.16.0+cu121 -f

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-f option requires 1 argument


It can't be installed

**Comment by ogkalu2** [comment]
The links are part of the pip install. you didn't add the links. copy each line entirely.

pip install torch==2.1.0+cu121 -f https://download.pytorch.org/whl/torch_stable.html

pip install torchvision==0.16.0+cu121 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by BomberCreeper** [comment]
Thanks, that helped. I opened a program.
