### ISSUE TITLE
Thanks for the big update! Need minor edit =)

### ISSUE THREAD

**Issue by TaunT** [ogkalu2/comic-translate#90]
You forgot add new module "DayuPath" to requirements.txt

I got an error `ModuleNotFoundError: No module named 'dayu_path'` on start and fix it by `pip install dayu-path`

**Comment by TaunT** [comment]
Unfortunately, the functionality of manual block editing cannot be used yet, some existing blocks can be selected only after 10-20 times, some are not selected at all
![image](https://github.com/user-attachments/assets/3d2ff545-488d-424a-9f6e-510536989a3c)

**Comment by TaunT** [comment]
3. After I pressed this button to go back a step - everything reset (( The upper buttons for moving through stages (translation, block search) became inactive, that is, nothing more can be done in the application, I had to close it and do everything from the very beginning
![image](https://github.com/user-attachments/assets/a4540888-b4f1-4c96-8638-1775a18f4073)

**Comment by TaunT** [comment]
Original image just in case
![RCO008-gigapixel-low resolution v2-2x HARD](https://github.com/user-attachments/assets/c74d638a-b6f6-421b-b804-c582245bd7df)

**Comment by TaunT** [comment]
4. It seems to me that the step "Get translations" should be moved almost to the very end before "Insert translations", because the API call is paid, and now after the translations there are complex blocks "Segment text" and "Clear image", where many things can go wrong and the attempt will be ruined

**Comment by TaunT** [comment]
5. Everything is bad :( Manual cleaning does not affect anything, the text is still inserted into a poorly cleaned image.
6. The worst thing is that the result cannot be saved, I click the Export button, select a folder, file name, but a new file is not created.

**Comment by TaunT** [comment]
Everything stopped working. I looked at the log - there are errors. The only thing I can do is close the application and start all over again. Sadly, I spent an hour trying to translate one page) It is impossible to use in its current form, an update is needed)

```
Traceback (most recent call last):
  File "c:\Python\comic-translate\comic.py", line 414, in load_segmentation_points
    if segm_pts.size > 0:
AttributeError: 'NoneType' object has no attribute 'size'
```

```
Traceback (most recent call last):
  File "c:\Python\comic-translate\comic.py", line 226, in finish_ocr_translate
    self.image_viewer.select_rectangle(rect)
  File "c:\Python\comic-translate\app\ui\image_viewer.py", line 485, in select_rectangle
    rect.setBrush(QtGui.QBrush(QtGui.QColor(255, 0, 0, 100)))  # Transparent red
AttributeError: 'NoneType' object has no attribute 'setBrush'
```

```

**Comment by ogkalu2** [comment]
File Saving is fixed. as for manual cleaning, this is what i managed.... 
![en_to_ru](https://github.com/user-attachments/assets/c0b2b6d1-6dc2-4403-a011-e7fca79cbc93)
- You have to draw the brush strokes yourself. Don't use the button
- You might have to run and draw multiple times
- Changing the Inpaint strategy to Original in settings will give the best output but it is very compute intensive. If you don't have a GPU, your system may crash with very high resolution images. CPU is very slow and lags.
- The alternative is to keep the strategy at resize but increase the limit from 640 to say...940 or something.

**Comment by TaunT** [comment]
Thanks for the answer! I'll try again later today. I really want to continue experimenting, but my child pulls me outside for a walk)

**Comment by TaunT** [comment]
After I corrected the translations and clicked "Segment text" (the next step), everything froze, there was an error in the log.
```
Traceback (most recent call last):
  File "c:\Python\comic-translate\comic.py", line 412, in load_segmentation_points
    if segm_pts.size > 0:
AttributeError: 'NoneType' object has no attribute 'size'
```
 Now I have to close the program and start all over again. What am I doing wrong? How can I proceed to manual block cleaning after translations?

**Comment by TaunT** [comment]
How can I proceed to manual block cleaning after translations?
When I go to the "Clean Image" tab, automatic cleaning starts immediately, and there is nothing to fix

**Comment by TaunT** [comment]
The current version is completely unworkable for me. In the previous one I could do something and then finish it in a graphic editor :`(

**Comment by TaunT** [comment]
If you navigate through the tabs of the top menu, each stage is automatically launched from the beginning without saving any changes. That is, you cannot go back and fix anything.
![image](https://github.com/user-attachments/assets/0802e88c-7bd2-4396-aff1-fcb287115855)

**Comment by TaunT** [comment]
Again a critical error at the step "Text segmentation"
```
Traceback (most recent call last):
  File "c:\Python\comic-translate\comic.py", line 412, in load_segmentation_points
    if segm_pts.size > 0:
AttributeError: 'NoneType' object has no attribute 'size'
```
I'm tired of trying for the 10th time, I'm giving up this useless activity and will wait for a new fixed version, sorry(
