### ISSUE TITLE
New update is incredible amazing !!

### ISSUE THREAD

**Issue by Sterben1579** [ogkalu2/comic-translate#91]
Hey buddy, this new update is incredible. I was absolutely blown away. Being able to edit the translated text already solves most of my problems.

I just have one small favor to ask. As you can see in the picture, some of the translated sentences are much smaller compared to the speech bubble and aren’t centered. If you could add a button like "Edit Bubbles" in addition to the buttons above, it would be awesome. With this button, if we could resize and reposition the text, that would be fantastic.

Here’s the example picture:

![image](https://github.com/user-attachments/assets/4f9b6882-4cdc-49e2-b0b7-8f46cdeb014b)

**Comment by Sterben1579** [comment]
Just a quick heads up.
In manual mode, after clicking 'detect bubbles,' I accidentally clicked 'translate.' Since I didn’t click the OCR button first, the system got stuck in a bug and doesn’t fix itself unless I restart it.

**Comment by ogkalu2** [comment]
https://github.com/user-attachments/assets/169275a1-44af-416b-8a54-55bb8722a580

The box that is generated right after cleaning is the box that the text will be rendered in. alter that to alter the size/position of the text. See the example video. Thanks for the heads up on the bug.

**Comment by Sterben1579** [comment]
Thanks, How can I increase the text size? I can change its position as you showed in the video, but the font size is too small. Also, to make it more readable, I need to move some parts to the next line. How can I do that?

**Comment by ogkalu2** [comment]
No typesetting right now

**Comment by untyper** [comment]
Agreed, this is an extremely useful tool. The gpt4o translation is way better than any machine translations I have seen.
Tool does the translation for you very nicely leaving you with just minimal work to edit and join up some image panels together

**Comment by TaunT** [comment]
> Just a quick heads up. In manual mode, after clicking 'detect bubbles,' I accidentally clicked 'translate.' Since I didn’t click the OCR button first, the system got stuck in a bug and doesn’t fix itself unless I restart it.

I accidentally discovered a lifehack - after a critical error, if you switch Manual mode to Automatic and back at the top, the program comes to life and you can proceed to the next step)

**Comment by Sterben1579** [comment]
> I accidentally discovered a lifehack - after a critical error, if you switch Manual mode to Automatic and back at the top, the program comes to life and you can proceed to the next step)

Right now, the only problem is the text size. It would be amazing if we could adjust the text size as well. On some pages, the text is so small that it is barely readable. Do you know any life hack for this?

**Comment by TaunT** [comment]
> Right now, the only problem is the text size. It would be amazing if we could adjust the text size as well. On some pages, the text is so small that it is barely readable. Do you know any life hack for this?

In automatic mode? I had this, but I started manually setting up the blocks and the problem went away

**Comment by TaunT** [comment]
And also, I really want the option to fix the font size. Sometimes this size is different in all blocks and it all looks strange together

**Comment by TaunT** [comment]
> Right now, the only problem is the text size. It would be amazing if we could adjust the text size as well. On some pages, the text is so small that it is barely readable. Do you know any life hack for this?

"why is the text sometimes very small" - the answer is simple, the program cannot wrap words, and if your block is narrow in width, the font is reduced to accommodate the longest word. Therefore, when setting up rectangles, try to increase the width more, even at the expense of the height. Or manually insert a hyphen "- " into long words
