### ISSUE TITLE
Dreams about features that I would also like to see in the program =)

### ISSUE THREAD

**Issue by TaunT** [ogkalu2/comic-translate#94]
1) ![image](https://github.com/user-attachments/assets/c1a4d1c0-752f-4d69-a0f6-3719c78c40d1)
Somewhere here there is a serious lack of scrollers to move between blocks of text at stages where this is no longer possible, that is, the last 3 stages - segments, cleaning, inserting translation

2) highlighting the active step
![image](https://github.com/user-attachments/assets/fae9dff3-cca0-4610-94e3-6dd609d0341c)

3) Automatic text centering according to block height.
![image](https://github.com/user-attachments/assets/35c3ccad-891a-473a-8f49-76d6fafb667d)
![image](https://github.com/user-attachments/assets/16ebf83e-5c2a-4c1b-84d9-3444765f6d4f)

4) option to fix font size

5) change text color for a separate block

**Comment by TaunT** [comment]
> I wanted to open an issue about these topics, but you have already said everything I wanted to say. Could you remind me if these updates are released?

I am not the developer of this application) Maybe I will try to do some simple things myself and create a merge request to practice in python

**Comment by TaunT** [comment]
@Sterben1579 I made all these improvements in my branch) to add them to the main program you need the owner's approval

**Comment by TaunT** [comment]
@ogkalu2 Good day! Another wish for future development, I don't know yet if I can do it myself. A "magnifying glass" type tool in manual mode - you point it at a cleared or translated image and it shows a piece of the original image in that place to compare the font size and bubble borders (which can be spoiled by clearing)
And what about merging my changes? Maybe you'll allow me to make a request and take a look?

**Comment by Sterben1579** [comment]
@TaunT  Good day!
The changes you made look fantastic. Can you share them with me? I do have one concern. In American comics, having the same text size might maintain visual consistency, but in Japanese manga, the text sizes vary constantly. Could you create something that allows us to adjust the font size according to the speech bubble? A feature where we can click on the text and change the size live, like 14-15px, would be amazing.

To take the idea even further, if we could adjust the position and size of the text by grabbing it from the corner, just like in Photoshop, it would take this program to the next level.

**Comment by TaunT** [comment]
@Sterben1579
> in Japanese manga, the text sizes vary constantly. Could you create something that allows us to adjust the font size according to the speech bubble? A feature where we can click on the text and change the size live, like 14-15px, would be amazing.

For this, I made the "maximum font" setting on the panel. This property was inside the program, but unchangeable and large = 40. 
If you leave the "fixed font" field empty and enter in the maximum, for example, 15, then the size will be selected automatically, but not more than 15. This helped me avoid too large texts.

![image](https://github.com/user-attachments/assets/d533ce8e-c964-45a8-929b-2a2528bf9f48)

**Comment by Sterben1579** [comment]
@TaunT Hi again.
The issue for us isn’t that the font is too big, but that it’s too small. Setting the minimum font size to 13 should solve this problem. However, while translating, sentences that are lengthy in English can be much shorter in Turkish. When this happens, the text looks tiny inside the large speech bubble.

Can we solve this by adding an extra step to the menu? Placing an "Edit Translations" button to the left of the "Paste Translations" menu, where we can adjust the text size and position before pasting it into the image, would be much better.

**Comment by TaunT** [comment]
@Sterben1579 Hello again)
I have already written in another place, it seems to me that the problem here is not in the minimum font size, but in long words. The program cannot do hyphenation automatically, so the entire text is adjusted so that the longest word fits into the block by width. Try replacing the word with a shorter synonym or manually insert a hyphen "- " (hyphen and space) into it. Or increase the text block so that it goes beyond the border. Then one longest word can overlap the border, then all the others will look fine.
If you try to set the minimum size, the effect will be the same.

**Comment by ogkalu2** [comment]
@TaunT @Sterben1579
For your Changes
- I prefer adding a button to re-draw the rectangles in the blk_list rather than messing with Undo/Redo and adding Next/Previous buttons. I've pushed this and won't be merging your changes on that.
- You can share your changes for setting a fixed font size but i'm not sure if i'll add it as is.

Text wrapping should be capable of breaking words (just not by default). 
In modules.rendering.render, line 50:
set break_long_words=False to True
you can also set break_on_hyphens and/or hyphenate_broken_words to True

I will make this changeable from the app later

**Comment by TaunT** [comment]
@ogkalu2 Well, I don't know, it seems strange to me to make a redrawing of blocks by a button, when it is always necessary and should be automatic, besides, for the Undo button it is done by inserting 3 lines of code.

![image](https://github.com/user-attachments/assets/55b6ed3d-fac5-45d0-85b4-f7e3bb34d825)

For one page, I now have to press the Cancel button 5-7 times after inserting translations to move the blocks so that the text in them looks neater and is centered, and in your opinion, I have to press 2 buttons each time instead of one.
By the way, this is all because of the problem with centering, even though the block is made along the borders of the cloud, the text is still not centered, so I have to move it to make it even.

1) the blocks are straight
![image](https://github.com/user-attachments/assets/4268222b-f4d1-4793-a231-6034f6a96106)

2) the text is inserted crookedly
![image](https://github.com/user-attachments/assets/b9453862-9e87-429e-94aa-53985eba2809)

3) I have to move the block
![image](https://github.com/user-attachments/assets/9b158d2a-3d6b-4f9a-944c-5a256ae502c7)

4) so ​​that the text is straight
![image](https://github.com/user-attachments/assets/95e7f593-a7dc-45d4-8a9f-83ff78d36539)

Therefore (well, also because of the translation editing) it is not possible to use the program in automatic mode yet =(
