### ISSUE TITLE
Is there a way to increase the size of pasted letters?

### ISSUE THREAD

**Issue by Asradda** [ogkalu2/comic-translate#95]
When pasted after translation, some characters are printed too small. Is there a way to increase the size of the characters?

**Comment by TaunT** [comment]
Try to enlarge the text block, even beyond the white cloud borders. And also insert a hyphen in the longest word.

**Comment by ogkalu2** [comment]
@Asradda 
The latest update has a "minimum font size" setting in Settings > Text Rendering now
